Sunbird-Obsrv/sunbird-data-pipeline

devops/roles/data-products-deploy/templates/common.conf.j2
devops/roles/data-products-deploy/templates/model-config.j2

@anandp504 
I have added  configuration to run portal-metrics data-product please review this once and let me if any changes are needed.

Model configurations update to run portal-metrics data product

---

devops/roles/data-products-deploy/templates/model-config.j2
devops/roles/data-products-deploy/templates/model-config.json.j2
devops/roles/data-products-deploy/templates/submit-all-jobs.rb.j2

@anandp504  This PR is related to added `etb-coverage-summary`,`dialcode-usage-summary` and `portal-metrics` to model config

Issue SB-9190 fix:Model config update

---

data-pipeline/de-duplication/pom.xml
data-pipeline/es-indexer/pom.xml
data-pipeline/telemetry-extractor/pom.xml
data-pipeline/telemetry-location-updater/pom.xml
data-pipeline/telemetry-router/pom.xml
data-pipeline/telemetry-validator/pom.xml

changes:
- upgrade the job version to reflect the changes during build

Issue #SB-9610 fix: pipeline job build optimization

---

Jenkinsfile

Issue #000 feat: Removed log rotation

---

data-pipeline/distribution/pom.xml
data-pipeline/telemetry-location-updater/pom.xml
data-pipeline/telemetry-location-updater/src/main/java/org/ekstep/ep/samza/domain/Location.java
data-pipeline/telemetry-location-updater/src/main/java/org/ekstep/ep/samza/util/LocationCache.java
data-pipeline/telemetry-location-updater/src/main/java/org/ekstep/ep/samza/util/UserLocationCache.java

changes:
- null check before pushing it to redis

Issue #SB-10412 fix: user location not stamped to telemetry

---

data-pipeline/distribution/pom.xml
data-pipeline/redis-updater/pom.xml
data-pipeline/redis-updater/src/main/config/redis-updater.properties
data-pipeline/redis-updater/src/main/java/org/ekstep/ep/samza/service/RedisUpdaterService.java
data-pipeline/redis-updater/src/main/java/org/ekstep/ep/samza/task/RedisUpdaterTask.java
data-pipeline/redis-updater/src/test/java/org/ekstep/ep/samza/service/RedisUpdaterServiceTest.java

changes:
- pipeline metrics config changes

Issue #SB-10366 update:  redis updater

---

devops/roles/data-products-deploy/templates/model-config.j2
devops/roles/data-products-deploy/templates/submit-all-jobs.rb.j2

@sowmya-dixit @sunilpes Please review the PR

Issue #0000 fix: Added ETB coverage summary job

---

ansible/roles/data-products-deploy/templates/model-config.j2
ansible/roles/data-products-deploy/templates/submit-all-jobs.rb.j2

@sowmya-dixit @sunilpes Please review

Issue #0000 fix: Added ETB coverage summary job to ansible directory

---

data-pipeline/de-duplication/pom.xml
data-pipeline/distribution/pom.xml
data-pipeline/es-indexer/pom.xml
data-pipeline/telemetry-extractor/pom.xml
data-pipeline/telemetry-location-updater/pom.xml
data-pipeline/telemetry-router/pom.xml
data-pipeline/telemetry-validator/pom.xml

@anandp504 .Changed the samza version.Please review

Samza consumerlag metrics

---

data-pipeline/de-duplication/pom.xml
data-pipeline/distribution/pom.xml
data-pipeline/ep-core/src/main/java/org/ekstep/ep/samza/core/JobMetrics.java
data-pipeline/ep-core/src/test/java/org/ekstep/ep/samza/fixtures/MetricsFixture.java
data-pipeline/ep-core/src/test/java/org/ekstep/ep/samza/task/JobMetricsTest.java
data-pipeline/es-indexer/pom.xml
data-pipeline/telemetry-extractor/pom.xml
data-pipeline/telemetry-location-updater/pom.xml
data-pipeline/telemetry-router/pom.xml
data-pipeline/telemetry-validator/pom.xml

Issue #SC-924 fix: Fix consumer lag when there are no events in the stream

---

ansible/roles/ep_logstash/templates/logstash.conf.indexer.pipeline_metrics

This changes is required to pull the lag metrics to 
influxdb and show it in grafana.

updated the logstash pipeline metrics config file

---

data-pipeline/druid-events-validator/src/main/resources/schemas/summary/common.json

`Druid Events Validator Samza job` as  deployed properly with latest change in the both `prod` and `staging` env but in the last pull request I have created a pull request by skipping one of my local commit.
previous pr link: https://github.com/project-sunbird/sunbird-data-pipeline/pull/74

Summary Event Version Issue fix

---

data-pipeline/de-normalization/src/main/java/org/ekstep/ep/samza/service/DeNormalizationService.java
data-pipeline/de-normalization/src/main/java/org/ekstep/ep/samza/task/DeNormalizationSink.java
data-pipeline/de-normalization/src/main/java/org/ekstep/ep/samza/task/DeNormalizationSource.java
data-pipeline/de-normalization/src/test/java/org/ekstep/ep/samza/task/DeNormalizationTaskTest.java
data-pipeline/druid-events-validator/src/main/java/org/ekstep/ep/samza/task/DruidEventsValidatorSink.java
data-pipeline/druid-events-validator/src/main/java/org/ekstep/ep/samza/task/DruidEventsValidatorSource.java
data-pipeline/druid-events-validator/src/test/java/org/ekstep/ep/samza/task/SummaryEventsValidatorTaskTest.java
data-pipeline/druid-events-validator/src/test/java/org/ekstep/ep/samza/task/TelemetryEventsValidatorTaskTest.java
data-pipeline/events-router/src/main/config/events-router.properties
data-pipeline/events-router/src/main/java/org/ekstep/ep/samza/service/EventsRouterService.java
data-pipeline/events-router/src/main/java/org/ekstep/ep/samza/task/EventsRouterSink.java
data-pipeline/events-router/src/main/java/org/ekstep/ep/samza/task/EventsRouterSource.java
data-pipeline/events-router/src/test/java/org/ekstep/ep/samza/task/EventsRouterTaskTest.java
data-pipeline/redis-updater/src/main/java/org/ekstep/ep/samza/service/RedisUpdaterService.java
data-pipeline/redis-updater/src/main/java/org/ekstep/ep/samza/task/RedisUpdaterSink.java
data-pipeline/redis-updater/src/main/java/org/ekstep/ep/samza/task/RedisUpdaterSource.java

Issue #SC-924 feat: Poc SamzaConsumer Lag for druid jobs

---

data-pipeline/telemetry-location-updater/src/test/java/org/ekstep/ep/samza/task/TelemetryLocationUpdaterTaskTest.java
data-pipeline/telemetry-validator/src/main/java/org/ekstep/ep/samza/domain/Event.java
data-pipeline/telemetry-validator/src/main/java/org/ekstep/ep/samza/service/TelemetryValidatorService.java
data-pipeline/telemetry-validator/src/main/java/org/ekstep/ep/samza/task/TelemetryValidatorTask.java
data-pipeline/telemetry-validator/src/test/java/org/ekstep/ep/samza/fixtures/EventFixture.java
data-pipeline/telemetry-validator/src/test/java/org/ekstep/ep/samza/task/TelemetryValidatorTaskTest.java

Issue #SB-11569 feat: UserId correction in telemetry for federated users

---

ansible/roles/setup-kafka/defaults/main.yml

Added the lms related kafka topic

Feat DO-717: added the lms related kafka topic

---

devops/roles/lpa-telemetry-backup-deploy/templates/secor.common.j2

Issue #SC-961 feat: Change default timezone for secor backups to IST

---

pipelines/provision/druid/Jenkinsfile

This addition is required for provision the 
druid infrastructure

Added the druid provision jenkinsfile

---

ansible/roles/analytics-druid/defaults/main.yml

Issue #SC-966 feat: Refactor ansible variables for druid provisioning

---

ansible/druid-provision.yml
ansible/roles/analytics-druid/files/whitelist

Druid ansible scripts

---

ansible/druid-provision.yml
ansible/roles/analytics-druid/tasks/main.yml
ansible/roles/druid_graphite/tasks/main.yml
ansible/roles/druid_graphite/templates/opt/graphite/webapp/graphite/local_settings.py.j2
ansible/roles/postgres-provision/defaults/main.yml
pipelines/provision/druid/Jenkinsfile

Updated the secrets path and variable as per the new 
inventory structure. Also removed one line from from postgres
defaults.

Updated ansible variables related to druid provisioning role

---

data-pipeline/distribution/pom.xml
data-pipeline/telemetry-validator/pom.xml

Issue #11569 feat: Bump up the version for telemetry validator job

---

ansible/roles/setup-kafka/defaults/main.yml
data-pipeline/de-normalization/src/main/config/de-normalization.properties
data-pipeline/de-normalization/src/main/java/org/ekstep/ep/samza/service/DeNormalizationService.java
data-pipeline/de-normalization/src/main/java/org/ekstep/ep/samza/task/DeNormalizationTask.java
data-pipeline/de-normalization/src/test/java/org/ekstep/ep/samza/fixtures/EventFixture.java
data-pipeline/de-normalization/src/test/java/org/ekstep/ep/samza/task/DeNormalizationTaskTest.java
data-pipeline/events-router/src/main/config/events-router.properties
data-pipeline/events-router/src/main/java/org/ekstep/ep/samza/service/EventsRouterService.java
data-pipeline/events-router/src/main/java/org/ekstep/ep/samza/task/EventsRouterConfig.java
data-pipeline/events-router/src/main/java/org/ekstep/ep/samza/task/EventsRouterSink.java
data-pipeline/events-router/src/test/java/org/ekstep/ep/samza/fixtures/EventFixture.java
data-pipeline/events-router/src/test/java/org/ekstep/ep/samza/task/EventsRouterTaskTest.java
druid/ingestion-spec/log-index-kafka.json

@anandp504 @sowmya-dixit @sunilpes Please review.

Issue #SC-963 chore: Update samza jobs for ingesting LOG events to druid

---

ansible/roles/lpa-telemetry-backup-deploy/templates/secor.common.j2
ansible/roles/secor-deploy/tasks/main.yml

Issue #SC-961 feat: Changes to specify timezone for secor parser

---

ansible/roles/lpa-telemetry-backup-deploy/tasks/main.yml

Issue #SC-961 feat: Change secor version to 0.25 for secor backups

---

ansible/roles/secor-deploy/templates/secor-service.j2

Issue #SC-961 feat: Changes secor version in secor start/stop scripts

---

data-pipeline/de-normalization/src/main/java/org/ekstep/ep/samza/domain/Event.java
data-pipeline/de-normalization/src/main/java/org/ekstep/ep/samza/service/DeNormalizationService.java
data-pipeline/de-normalization/src/test/java/org/ekstep/ep/samza/fixtures/EventFixture.java
data-pipeline/de-normalization/src/test/java/org/ekstep/ep/samza/task/DeNormalizationTaskTest.java
druid/ingestion-spec/log-index-kafka.json

@anandp504 @sowmya-dixit @sunilpes Please review

Issue #SC-963 chore: Update denormalization job to filter LOG events with type 'api_access'

---

data-pipeline/de-normalization/src/main/config/de-normalization.properties

Issue #SC-963 update: Update redis db index in denormalization job

---

data-pipeline/distribution/pom.xml

Issue #SC-993 feat: Add druid events validator job to distribution

---

ansible/roles/analytics-druid/defaults/main.yml

Issue #SC-824 Feat: Fix the path for middlemanger

---

ansible/roles/samza-jobs/defaults/main.yml

Issue #000 feat: Add redis_host group var variable

---

ansible/roles/samza-jobs/defaults/main.yml
data-pipeline/druid-events-validator/src/main/resources/schemas/summary/contentdata.json
data-pipeline/druid-events-validator/src/main/resources/schemas/telemetry/contentdata.json
druid/ingestion-spec/summary_index_kafka.json
druid/ingestion-spec/telemetry_index_kafka.json

Issue #000 feat: Add subject and grade to druid ingestion spec

---

data-pipeline/distribution/pom.xml
data-pipeline/druid-events-validator/pom.xml
data-pipeline/druid-events-validator/src/main/java/org/ekstep/ep/samza/domain/Event.java
data-pipeline/druid-events-validator/src/main/java/org/ekstep/ep/samza/task/DruidEventsValidatorSink.java
data-pipeline/events-router/pom.xml
data-pipeline/events-router/src/main/java/org/ekstep/ep/samza/domain/Event.java
data-pipeline/events-router/src/main/java/org/ekstep/ep/samza/service/EventsRouterService.java

This pull request is only for the load test and will revert this code once the load test is done

Issue #000 fix: Load Test

---

ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/tasks/main.yml
ansible/roles/data-products-deploy/templates/model-config.j2
ansible/roles/data-products-deploy/templates/submit-all-jobs.rb.j2

@sowmya-dixit @sunilpes @anandp504 Please review

Issue #SB-11295 fix: Add cron job for course-metrics job

---

data-pipeline/distribution/pom.xml
data-pipeline/telemetry-validator/pom.xml
data-pipeline/telemetry-validator/src/main/java/org/ekstep/ep/samza/service/TelemetryValidatorService.java

Issue #000 feat: Remove skipping learning platform log events

---

data-pipeline/de-duplication/pom.xml
data-pipeline/de-duplication/src/main/config/de-duplication.properties
data-pipeline/de-normalization/pom.xml
data-pipeline/de-normalization/src/main/config/de-normalization.properties
data-pipeline/distribution/pom.xml
data-pipeline/druid-events-validator/pom.xml
data-pipeline/druid-events-validator/src/main/config/druid-events-validator.properties
data-pipeline/events-router/pom.xml
data-pipeline/events-router/src/main/config/events-router.properties
data-pipeline/redis-updater/pom.xml
data-pipeline/redis-updater/src/main/config/redis-updater.properties
data-pipeline/telemetry-extractor/pom.xml
data-pipeline/telemetry-extractor/src/main/config/telemetry-extractor.properties
data-pipeline/telemetry-location-updater/pom.xml
data-pipeline/telemetry-location-updater/src/main/config/telemetry-location-updater.properties
data-pipeline/telemetry-router/pom.xml
data-pipeline/telemetry-router/src/main/config/telemetry-router.properties
data-pipeline/telemetry-validator/pom.xml
data-pipeline/telemetry-validator/src/main/config/telemetry-validator.properties

Issue #SC-000 Fix: Fixed the default metrics issue in jobs

---

ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/templates/model-config.j2

@anandp504 @sunilpes @sowmya-dixit Please review

Issue #SB-SB-10800 chore: Add telemetry replay job

---

ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/templates/model-config.j2

@anandp504 @sunilpes @sowmya-dixit Please review

Issue #SB-SB-10800 chore: Update output topic name

---

data-pipeline/de-duplication/pom.xml
data-pipeline/de-duplication/src/main/config/de-duplication.properties
data-pipeline/de-duplication/src/main/java/org/ekstep/ep/samza/engine/DeDupEngine.java
data-pipeline/de-duplication/src/main/java/org/ekstep/ep/samza/service/DeDuplicationService.java
data-pipeline/de-duplication/src/main/java/org/ekstep/ep/samza/task/DeDuplicationConfig.java
data-pipeline/de-duplication/src/main/java/org/ekstep/ep/samza/task/DeDuplicationSink.java
data-pipeline/de-duplication/src/main/java/org/ekstep/ep/samza/task/DeDuplicationTask.java
data-pipeline/de-duplication/src/test/java/org/ekstep/ep/samza/task/DeDuplicationTaskTest.java
data-pipeline/de-normalization/pom.xml
data-pipeline/de-normalization/src/main/config/de-normalization.properties
data-pipeline/de-normalization/src/main/java/org/ekstep/ep/samza/task/DeNormalizationSink.java
data-pipeline/distribution/pom.xml
data-pipeline/druid-events-validator/pom.xml
data-pipeline/druid-events-validator/src/main/config/druid-events-validator.properties
data-pipeline/druid-events-validator/src/main/java/org/ekstep/ep/samza/task/DruidEventsValidatorSink.java
data-pipeline/events-router/pom.xml
data-pipeline/events-router/src/main/config/events-router.properties
data-pipeline/events-router/src/main/java/org/ekstep/ep/samza/task/EventsRouterSink.java
data-pipeline/redis-updater/pom.xml
data-pipeline/telemetry-extractor/pom.xml
data-pipeline/telemetry-extractor/src/main/config/telemetry-extractor.properties
data-pipeline/telemetry-location-updater/pom.xml
data-pipeline/telemetry-location-updater/src/main/config/telemetry-location-updater.properties
data-pipeline/telemetry-location-updater/src/main/java/org/ekstep/ep/samza/task/TelemetryLocationUpdaterSink.java
data-pipeline/telemetry-router/pom.xml
data-pipeline/telemetry-router/src/main/config/telemetry-router.properties
data-pipeline/telemetry-router/src/main/java/org/ekstep/ep/samza/task/TelemetryRouterSink.java
data-pipeline/telemetry-validator/pom.xml
data-pipeline/telemetry-validator/src/main/config/telemetry-validator.properties
data-pipeline/telemetry-validator/src/main/java/org/ekstep/ep/samza/task/TelemetryValidatorSink.java

RevertDeduplication

---

ansible/lpa_submit_all_jobs.yml
ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/templates/model-config.j2
ansible/roles/samza-logs-orphan/templates/orphan_process
ansible/roles/setup-kafka/defaults/main.yml
data-pipeline/de-duplication/pom.xml
data-pipeline/de-duplication/src/main/config/de-duplication.properties
data-pipeline/de-normalization/pom.xml
data-pipeline/de-normalization/src/main/config/de-normalization.properties
data-pipeline/de-normalization/src/test/java/org/ekstep/ep/samza/fixtures/EventFixture.java
data-pipeline/distribution/pom.xml
data-pipeline/druid-events-validator/pom.xml
data-pipeline/druid-events-validator/src/main/config/druid-events-validator.properties
data-pipeline/druid-events-validator/src/main/java/org/ekstep/ep/samza/task/DruidEventsValidatorSink.java
data-pipeline/events-router/pom.xml
data-pipeline/events-router/src/main/config/events-router.properties
data-pipeline/redis-updater/pom.xml
data-pipeline/redis-updater/src/main/config/redis-updater.properties
data-pipeline/telemetry-extractor/pom.xml
data-pipeline/telemetry-extractor/src/main/config/telemetry-extractor.properties
data-pipeline/telemetry-location-updater/pom.xml
data-pipeline/telemetry-location-updater/src/main/config/telemetry-location-updater.properties
data-pipeline/telemetry-location-updater/src/main/java/org/ekstep/ep/samza/util/RedisConnect.java
data-pipeline/telemetry-router/pom.xml
data-pipeline/telemetry-router/src/main/config/telemetry-router.properties
data-pipeline/telemetry-validator/pom.xml
data-pipeline/telemetry-validator/src/main/config/telemetry-validator.properties
data-pipeline/telemetry-validator/src/main/java/org/ekstep/ep/samza/service/TelemetryValidatorService.java

Issue #000 feat: Rebase from release-2.0 branch

---

ansible/dp_kafka_provision.yml
ansible/dp_zookeeper_provision.yml
pipelines/provision/kafka/Jenkinsfile
pipelines/provision/zookeeper/Jenkinsfile

This addition is required to provision the ingestion kafka 
cluster.

Added the Kafka provision related ansible script

---

data-pipeline/de-duplication/src/main/java/org/ekstep/ep/samza/service/DeDuplicationService.java
data-pipeline/druid-processor/src/main/java/org/ekstep/ep/samza/service/DruidProcessorService.java
data-pipeline/redis-updater/src/main/java/org/ekstep/ep/samza/service/RedisUpdaterService.java
data-pipeline/telemetry-extractor/src/main/java/org/ekstep/ep/samza/task/TelemetryExtractorTask.java
data-pipeline/telemetry-location-updater/src/main/java/org/ekstep/ep/samza/service/TelemetryLocationUpdaterService.java
data-pipeline/telemetry-router/src/main/java/org/ekstep/ep/samza/service/TelemetryRouterService.java
data-pipeline/telemetry-validator/src/main/java/org/ekstep/ep/samza/service/TelemetryValidatorService.java

Issue #SC-924 Fix: Fixed the Consumer_lag setting offset before return

---

ansible/roles/data-products-deploy/templates/common.conf.j2
ansible/roles/data-products-deploy/templates/model-config.j2
ansible/roles/data-products-deploy/templates/model-config.json.j2
druid/ingestion-spec/telemetry_feedback_index_kafka.json

@anandp504 @sunilpes Please review

Content Rating DataProduct Configurations

---

data-pipeline/de-duplication/pom.xml
data-pipeline/de-duplication/src/main/java/org/ekstep/ep/samza/service/DeDuplicationService.java
data-pipeline/de-normalization/pom.xml
data-pipeline/de-normalization/src/main/java/org/ekstep/ep/samza/service/DeNormalizationService.java
data-pipeline/distribution/pom.xml
data-pipeline/druid-events-validator/pom.xml
data-pipeline/druid-events-validator/src/main/java/org/ekstep/ep/samza/service/DruidEventsValidatorService.java
data-pipeline/events-router/pom.xml
data-pipeline/events-router/src/main/java/org/ekstep/ep/samza/service/EventsRouterService.java
data-pipeline/redis-updater/pom.xml
data-pipeline/redis-updater/src/main/java/org/ekstep/ep/samza/service/RedisUpdaterService.java
data-pipeline/telemetry-extractor/pom.xml
data-pipeline/telemetry-extractor/src/main/java/org/ekstep/ep/samza/task/TelemetryExtractorTask.java
data-pipeline/telemetry-location-updater/src/main/java/org/ekstep/ep/samza/service/TelemetryLocationUpdaterService.java
data-pipeline/telemetry-router/pom.xml
data-pipeline/telemetry-router/src/main/java/org/ekstep/ep/samza/service/TelemetryRouterService.java
data-pipeline/telemetry-validator/pom.xml
data-pipeline/telemetry-validator/src/main/java/org/ekstep/ep/samza/service/TelemetryValidatorService.java

Issue #SC-000 Fix: Fixed the Consumer_lag setting offset

---

ansible/roles/data-products-deploy/templates/common.conf.j2

Issue #SB-10302 chore: fix get content list druid query

---

ansible/roles/data-products-deploy/templates/model-config.j2

Issue #SB-10302 chore: update start and end date for query

---

ansible/roles/data-products-deploy/templates/model-config.j2
ansible/roles/data-products-deploy/templates/submit-all-jobs.rb.j2

Issue #SB-10302 chore: enable content-rating-updater in job-manager

---

data-pipeline/de-duplication/src/main/java/org/ekstep/ep/samza/engine/DeDupEngine.java
data-pipeline/de-duplication/src/main/java/org/ekstep/ep/samza/service/DeDuplicationService.java
data-pipeline/de-duplication/src/main/java/org/ekstep/ep/samza/task/DeDuplicationTask.java
data-pipeline/de-duplication/src/test/java/org/ekstep/ep/samza/task/DeDuplicationTaskTest.java

Issue #SC-993 refactor: Redis connection changes

---

ansible/roles/analytics-api-deploy/templates/conf.j2

Issue #SB-11888 chore: Add metrics time interval to analytics api config

---

ansible/roles/cassandra-deploy/templates/data.cql.j2

Release 2.0.0

---

ansible/druid-ingestion.yml
ansible/inventory/env/group_vars/all.yml
ansible/roles/druid-ingestion/defaults/main.yml
ansible/roles/druid-ingestion/tasks/main.yml
ansible/roles/druid-ingestion/templates/log_index_kafka
ansible/roles/druid-ingestion/templates/summary_index_kafka
ansible/roles/druid-ingestion/templates/telemetry_index_kafka
pipelines/ops/druid/Jenkinsfile.ingestion

This addition is required to start the ingestion task and
stop the ingestion task.

Added the druid ingestion start task and stop task scripts

---

ansible/roles/analytics-api-deploy/templates/conf.j2

Issue #SB-11888 chore: Add ActorInjector play module

---

druid/ingestion-spec/telemetry_index_kafka.json

Issue #SB-11888 refactor: dialcodedata type change in telemetry ingestion spec

---

data-pipeline/de-duplication/src/main/java/org/ekstep/ep/samza/domain/Event.java
data-pipeline/de-duplication/src/main/java/org/ekstep/ep/samza/service/DeDuplicationService.java
data-pipeline/de-duplication/src/main/java/org/ekstep/ep/samza/task/DeDuplicationSink.java
data-pipeline/de-duplication/src/main/java/org/ekstep/ep/samza/task/DeDuplicationTask.java
data-pipeline/distribution/pom.xml
data-pipeline/ep-core/src/main/java/org/ekstep/ep/samza/core/JobMetrics.java
data-pipeline/events-router/src/main/java/org/ekstep/ep/samza/service/EventsRouterService.java
data-pipeline/redis-updater/pom.xml
data-pipeline/redis-updater/src/main/java/org/ekstep/ep/samza/service/RedisUpdaterService.java
data-pipeline/redis-updater/src/test/java/org/ekstep/ep/samza/service/RedisUpdaterServiceTest.java

Issue #SB-11888 feat: Refactor redis updater job

---

ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/templates/model-config.j2
ansible/roles/data-products-deploy/templates/replay-job.j2

@sunilpes @anandp504 Please review

Issue #000 fix: Updated scripts for replay job

---

data-pipeline/de-normalization/pom.xml
data-pipeline/de-normalization/src/main/java/org/ekstep/ep/samza/util/UserDataCache.java
data-pipeline/distribution/pom.xml
data-pipeline/telemetry-validator/pom.xml

@sunilpes @sowmya-dixit @RevathiKotla

Issue #SB-11888 fix: Fix cassandra cluster reconnect

---

data-pipeline/distribution/pom.xml
data-pipeline/telemetry-location-updater/pom.xml
data-pipeline/telemetry-location-updater/src/main/java/org/ekstep/ep/samza/domain/Location.java

Issue #SB-11888 fix: Update distribution pom.xml with correct versions

---

ansible/roles/redis/defaults/main.yml
ansible/roles/redis/templates/redis.conf.j2

Issue #000 feat: configuration for redis maxmemory

---

ansible/roles/analytics-api-provision/defaults/main.yml

Issue #SB-12811 fix: Make heap size for analytics api configurable

---

ansible/roles/druid-ingestion/defaults/main.yml
ansible/roles/druid-ingestion/templates/error_index_kafka
ansible/roles/setup-kafka/defaults/main.yml
data-pipeline/de-normalization/src/main/java/org/ekstep/ep/samza/service/DeNormalizationService.java
data-pipeline/de-normalization/src/test/java/org/ekstep/ep/samza/task/DeNormalizationTaskTest.java
data-pipeline/distribution/pom.xml
data-pipeline/events-router/pom.xml
data-pipeline/events-router/src/main/config/events-router.properties
data-pipeline/events-router/src/main/java/org/ekstep/ep/samza/service/EventsRouterService.java
data-pipeline/events-router/src/main/java/org/ekstep/ep/samza/task/EventsRouterConfig.java
data-pipeline/events-router/src/main/java/org/ekstep/ep/samza/task/EventsRouterSink.java
data-pipeline/events-router/src/test/java/org/ekstep/ep/samza/fixtures/EventFixture.java
data-pipeline/events-router/src/test/java/org/ekstep/ep/samza/task/EventsRouterTaskTest.java

Issue #SC-1011 chore: Druid ingestion changes for error events

---

ansible/roles/setup-kafka/defaults/main.yml

Change analytics.job_queue topic retention time to 8hrs

---

ansible/roles/analytics-api-deploy/templates/conf.j2
ansible/roles/ep_logstash/defaults/main.yml
ansible/roles/ep_logstash/templates/logstash.conf.indexer.device_api_metrics

Issue #000 fix: Disable kafka appender and use logstash

---

data-pipeline/telemetry-extractor/pom.xml
data-pipeline/telemetry-validator/pom.xml

Issue #SC-000 fix: Changed the Samza Version to 0.14.1

---

ansible/roles/data-products-deploy/templates/model-config.j2
ansible/roles/data-products-deploy/templates/submit-all-jobs.rb.j2

Disable unused data products.

---

ansible/roles/ep_logstash/templates/logstash.conf.indexer.pipeline_metrics
data-pipeline/de-duplication/src/main/java/org/ekstep/ep/samza/task/DeDuplicationSink.java
data-pipeline/ep-core/src/main/java/org/ekstep/ep/samza/core/JobMetrics.java
data-pipeline/events-router/src/main/java/org/ekstep/ep/samza/task/EventsRouterSink.java
data-pipeline/telemetry-extractor/src/main/java/org/ekstep/ep/samza/task/TelemetryExtractorSink.java

@anandp504 @sowmya-dixit Please review

Issue #SC-000 Feat: Added new Metrics for Duplicate Events

---

ansible/roles/cassandra-deploy/templates/data.cql.j2

@anandp504 @sunilpes Please review

Add fcm_token and producer_id columns to device_profile cassandra table

---

ansible/redis-backup.yml
ansible/roles/azure-cli/tasks/main.yml
ansible/roles/redis-backup/defaults/main.yml
ansible/roles/redis-backup/meta/main.yml
ansible/roles/redis-backup/tasks/main.yml
pipelines/backup/redis-backup/Jenkinsfile

added ansible role and jenkins file for redis backup

Redis backup

---

ansible/roles/ep_logstash/templates/logstash.conf.indexer.analytics_metrics
ansible/roles/ep_logstash/templates/logstash.conf.indexer.learning
ansible/roles/ep_logstash/templates/logstash.conf.indexer.partner
ansible/roles/ep_logstash/templates/logstash.conf.indexer.pipeline_metrics
ansible/roles/ep_logstash/templates/logstash.conf.indexer.public

@sowmya-dixit @anandp504 Please review

Issue #SC-000 Feat: Added missing dot for logstash pipeline metrics

---

data-pipeline/distribution/pom.xml
data-pipeline/telemetry-location-updater/pom.xml
data-pipeline/telemetry-location-updater/src/main/java/org/ekstep/ep/samza/util/DeviceProfileCache.java

Issue #SC-1028 fix: Fixed the exception cases for first_access

---

data-pipeline/distribution/pom.xml
data-pipeline/redis-updater/pom.xml

Issue #SC-000 fix: Updating the version

---

data-pipeline/de-normalization/src/main/java/org/ekstep/ep/samza/service/DeNormalizationService.java
data-pipeline/de-normalization/src/main/java/org/ekstep/ep/samza/util/DataCache.java
data-pipeline/de-normalization/src/main/java/org/ekstep/ep/samza/util/UserDataCache.java
data-pipeline/distribution/pom.xml
data-pipeline/ep-core/src/main/java/org/ekstep/ep/samza/util/RedisConnect.java
data-pipeline/events-router/pom.xml
data-pipeline/events-router/src/main/java/org/ekstep/ep/samza/domain/DeDupEngine.java
data-pipeline/events-router/src/main/java/org/ekstep/ep/samza/service/EventsRouterService.java
data-pipeline/redis-updater/src/main/java/org/ekstep/ep/samza/service/RedisUpdaterService.java
data-pipeline/telemetry-extractor/src/main/config/telemetry-extractor.properties
data-pipeline/telemetry-extractor/src/main/java/org/ekstep/ep/samza/service/TelemetryExtractorService.java
data-pipeline/telemetry-extractor/src/main/java/org/ekstep/ep/samza/task/TelemetryExtractorConfig.java
data-pipeline/telemetry-extractor/src/main/java/org/ekstep/ep/samza/task/TelemetryExtractorTask.java
data-pipeline/telemetry-extractor/src/test/java/org/ekstep/ep/samza/task/TelemetryExtractorTaskTest.java
data-pipeline/telemetry-location-updater/src/main/java/org/ekstep/ep/samza/service/TelemetryLocationUpdaterService.java
data-pipeline/telemetry-location-updater/src/main/java/org/ekstep/ep/samza/util/DeviceProfileCache.java

@sowmya-dixit @sunilpes Please Review

Release-2.0.5  -> merge -> Release 2.1.0

---

ansible/roles/druid-ingestion/templates/log_index_kafka
ansible/roles/druid-ingestion/templates/summary_index_kafka
ansible/roles/druid-ingestion/templates/telemetry_feedback_index_kafka
ansible/roles/druid-ingestion/templates/telemetry_index_kafka

Rename device denom fields in druid ingestion spec

---

ansible/roles/cassandra-deploy/templates/data.cql.j2

@sowmya-dixit  @sunilpes Please review

Issue #SC-000 : Removing channel from Device Profile Table

---

data-pipeline/de-duplication/pom.xml
data-pipeline/de-duplication/src/main/java/org/ekstep/ep/samza/service/DeDuplicationService.java
data-pipeline/de-normalization/pom.xml
data-pipeline/de-normalization/src/main/java/org/ekstep/ep/samza/service/DeNormalizationService.java
data-pipeline/distribution/pom.xml
data-pipeline/druid-events-validator/pom.xml
data-pipeline/druid-events-validator/src/main/java/org/ekstep/ep/samza/service/DruidEventsValidatorService.java
data-pipeline/ep-core/src/main/java/org/ekstep/ep/samza/core/BaseSink.java
data-pipeline/ep-core/src/main/java/org/ekstep/ep/samza/core/JobMetrics.java
data-pipeline/ep-core/src/test/java/org/ekstep/ep/samza/fixtures/MetricsFixture.java
data-pipeline/ep-core/src/test/java/org/ekstep/ep/samza/task/JobMetricsTest.java
data-pipeline/events-router/pom.xml
data-pipeline/events-router/src/main/java/org/ekstep/ep/samza/service/EventsRouterService.java
data-pipeline/redis-updater/pom.xml
data-pipeline/redis-updater/src/main/java/org/ekstep/ep/samza/service/RedisUpdaterService.java
data-pipeline/telemetry-extractor/pom.xml
data-pipeline/telemetry-extractor/src/main/java/org/ekstep/ep/samza/task/TelemetryExtractorTask.java
data-pipeline/telemetry-location-updater/src/main/java/org/ekstep/ep/samza/service/TelemetryLocationUpdaterService.java
data-pipeline/telemetry-router/pom.xml
data-pipeline/telemetry-router/src/main/java/org/ekstep/ep/samza/service/TelemetryRouterService.java
data-pipeline/telemetry-validator/pom.xml
data-pipeline/telemetry-validator/src/main/java/org/ekstep/ep/samza/service/TelemetryValidatorService.java

Issue #000 feat: Computing consumer lag for Samza jobs

---

ansible/roles/samza-jobs/defaults/main.yml

Issue #SC-000 : Added default value for pids dedup variable

---

ansible/roles/analytics-druid/defaults/main.yml

@RevathiKotla @sunilpes Please review

Upgrade druid to 0.15.0

---

ansible/druid-provision.yml
ansible/roles/analytics-druid/defaults/main.yml

@RevathiKotla @Kaali09 Please review

Ansible changes to use RDS postgres instance for druid

---

ansible/druid-provision.yml

Fix hosts for RDS postgres instance for druid

---

ansible/druid-provision.yml

Add secrets.yml file

---

ansible/druid-provision.yml
ansible/roles/analytics-druid/defaults/main.yml
ansible/roles/druid_graphite/templates/opt/graphite/webapp/graphite/local_settings.py.j2

Fix postgres user name for druid and graphite dbs.

---

ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/templates/submit-all-jobs.rb.j2

Re-schedule data products to run at 6AM

---

ansible/roles/data-products-deploy/defaults/main.yml

Re-schedule course-metrics to run at 2AM

---

pipelines/deploy/geolocation-db-setup/Jenkinsfile

Added the Email block to notify users the status of the build.

Adding Email Block

---

ansible/roles/data-products-deploy/templates/monitor-dp.j2
ansible/roles/secor-deploy/templates/monitor-secor.j2

@gandham-santhosh Please review the changes and approve

Remove slack webhook url and use variable instead

---

ansible/roles/analytics-druid/defaults/main.yml
ansible/roles/analytics-druid/templates/historical/runtime.properties

Adding historical cache configurations

---

ansible/druid-ingestion.yml
ansible/samza_jobs_kill.yml
pipelines/ops/samza/Jenkinsfile.killjob

This addition is to kill the samza jobs(single or multiple) through jenkins jobs.

Release 2.2.0

---

ansible/roles/analytics-druid/defaults/main.yml

@Kaali09 @RevathiKotla Please review

Update azure container name for druid GA instance

---

ansible/roles/druid-ingestion/templates/error_index_kafka
ansible/roles/druid-ingestion/templates/log_index_kafka
ansible/roles/druid-ingestion/templates/summary_index_kafka
ansible/roles/druid-ingestion/templates/telemetry_feedback_index_kafka
ansible/roles/druid-ingestion/templates/telemetry_index_kafka

Ingestion spec changes to read from kafka topic latest offset

---

data-pipeline/de-duplication/pom.xml
data-pipeline/de-normalization/pom.xml
data-pipeline/druid-events-validator/pom.xml
data-pipeline/events-router/pom.xml
data-pipeline/redis-updater/pom.xml
data-pipeline/telemetry-extractor/pom.xml
data-pipeline/telemetry-location-updater/pom.xml
data-pipeline/telemetry-router/pom.xml
data-pipeline/telemetry-validator/pom.xml

@sunilpes @sowmya-dixit @RevathiKotla

Issue #000 feat: Add jacoco plugin config for code coverage

---

ansible/druid-compaction.yml
ansible/roles/druid-compaction/defaults/main.yml
ansible/roles/druid-compaction/tasks/main.yml
ansible/roles/druid-compaction/templates/segments_compaction.j2

Issue #SC-1175 feat: Fix errors related to GNU date functions

---

ansible/roles/data-products-deploy/templates/model-config.j2
ansible/roles/data-products-deploy/templates/submit-all-jobs.rb.j2

Disable content rating updater job

---

ansible/roles/analytics-druid/defaults/main.yml
ansible/roles/analytics-druid/files/whitelist
ansible/roles/analytics-druid/templates/_common/common.runtime.properties
ansible/roles/druid-ingestion/templates/error_index_kafka
ansible/roles/druid-ingestion/templates/log_index_kafka
ansible/roles/druid-ingestion/templates/summary_index_kafka
ansible/roles/druid-ingestion/templates/telemetry_feedback_index_kafka
ansible/roles/druid-ingestion/templates/telemetry_index_kafka

Issue link : https://project-sunbird.atlassian.net/browse/SC-1180
@sunilpes @anandp504

analytics-druid ansible role change.

---

ansible/roles/lpa-telemetry-backup-deploy/defaults/main.yml

pipeline metrics secor backup interval changes

---

ansible/roles/analytics-api-deploy/templates/conf.j2
ansible/roles/cassandra-deploy/templates/data.cql.j2
ansible/roles/data-products-deploy/templates/common.conf.j2
ansible/roles/data-products-deploy/templates/model-config.j2
ansible/roles/data-products-deploy/templates/model-config.json.j2

Issue #SC-1098 Feat: Experiment API and Dataproduct config changes

---

ansible/roles/ep_logstash/defaults/main.yml
ansible/roles/ep_logstash/tasks/common.yml

This addition is required to upgrade the logstash.

Release 2.3.0

---

ansible/roles/druid-ingestion/templates/pipeline_metrics_index_kafka

 Issue #SC-1009: Ingesting pipeline metrics to druid

---

ansible/roles/data-products-deploy/templates/common.conf.j2

Issue #SC-000: Changing the swarm-manager ansible variable

---

ansible/roles/ep_logstash/defaults/main.yml

Updated the logstash home path as we upgraded the logstash version.

Issue #000 feat: updated the logstashhome path

---

ansible/inventory/env/group_vars/all.yml
ansible/roles/ep_logstash/templates/logstash.conf.indexer.device_api_metrics

Issue #SB-14300: fixes- added job name

---

data-pipeline/distribution/pom.xml

Issue #SB-14300: Added job name to distributor samza job

---

ansible/roles/samza-jobs-alert/files/samza-job-string

Adding the new job string to  get the samza jobs failure alert.

Issue #000 feat: added the coursebatch updater job string

---

ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/tasks/main.yml
ansible/roles/data-products-deploy/templates/common.conf.j2
ansible/roles/data-products-deploy/templates/model-config.j2
ansible/roles/data-products-deploy/templates/model-config.json.j2

Dependent PR : https://github.com/project-sunbird/sunbird-analytics/pull/133

[SB-14499]Assessment report data product configurations

---

data-pipeline/de-normalization/src/main/java/org/ekstep/ep/samza/util/UserDataCache.java
data-pipeline/de-normalization/src/test/java/org/ekstep/ep/samza/task/DeNormalizationTaskTest.java

Merging hot fix release-2.3.2 to release-2.4.0

---

ansible/roles/druid-ingestion/templates/summary_index_kafka
ansible/roles/druid-ingestion/templates/telemetry_index_kafka
data-pipeline/de-normalization/src/main/java/org/ekstep/ep/samza/domain/Event.java
data-pipeline/de-normalization/src/main/java/org/ekstep/ep/samza/service/DeNormalizationService.java

@RevathiKotla @sowmya-dixit Please review

#SB-14344: Added dimension spec for createdBy, createdFor and additional TextBook details

---

ansible/roles/druid-ingestion/templates/summary_index_kafka
ansible/roles/druid-ingestion/templates/telemetry_index_kafka
data-pipeline/druid-events-validator/src/main/resources/schemas/summary/collectiondata.json
data-pipeline/druid-events-validator/src/main/resources/schemas/summary/contentdata.json
data-pipeline/druid-events-validator/src/main/resources/schemas/telemetry/collectiondata.json
data-pipeline/druid-events-validator/src/main/resources/schemas/telemetry/contentdata.json

@sowmya-dixit @RevathiKotla  please review

#SB-14344: Changed the type of created_for field

---

ansible/roles/druid-ingestion/templates/summary_index_kafka
ansible/roles/druid-ingestion/templates/telemetry_index_kafka
data-pipeline/druid-events-validator/src/main/resources/schemas/summary/collectiondata.json
data-pipeline/druid-events-validator/src/main/resources/schemas/summary/contentdata.json
data-pipeline/druid-events-validator/src/main/resources/schemas/telemetry/collectiondata.json
data-pipeline/druid-events-validator/src/main/resources/schemas/telemetry/contentdata.json

#SB-14344: Changed createdby and createdfor field

---

data-pipeline/device-profile-updater/src/main/java/org/ekstep/ep/samza/task/DeviceProfileUpdaterTask.java

Changed job name from device-profile-updater to DeviceProfileUpdater in task

---

ansible/roles/ep_logstash/templates/logstash.conf.indexer.pipeline_metrics

Issue #000: Added partition to tags for influxdb

---

data-pipeline/assessment-aggregator/src/main/java/org/ekstep/ep/samza/domain/Aggregate.java
data-pipeline/assessment-aggregator/src/main/java/org/ekstep/ep/samza/service/AssessmentAggregatorService.java
data-pipeline/assessment-aggregator/src/main/java/org/ekstep/ep/samza/util/DBUtil.java
data-pipeline/assessment-aggregator/src/test/java/org/ekstep/ep/samza/task/AssessmentAggregatorTest.java

Issue #SB-13498 : Added grand_total column to assessment

---

ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/tasks/main.yml
ansible/roles/data-products-deploy/templates/start-jobmanager.j2

Script to make sure the killing of the job-manager process id before starting.
@sunilpes

Job manager update

---

ansible/roles/analytics-api-deploy/templates/conf.j2

Get DeviceProfileAPI cache refresh interval config

---

data-pipeline/device-profile-updater/src/main/java/org/ekstep/ep/samza/service/DeviceProfileUpdaterService.java

Device Profile Updater samza job fix

---

data-pipeline/events-router/src/test/java/org/ekstep/ep/samza/fixtures/EventFixture.java
data-pipeline/events-router/src/test/java/org/ekstep/ep/samza/task/EventsRouterTaskTest.java

Issue: #0000: Added test cases for improved code coverage

---

data-pipeline/assessment-aggregator/pom.xml
data-pipeline/assessment-aggregator/src/main/java/org/ekstep/ep/samza/service/AssessmentAggregatorService.java
data-pipeline/assessment-aggregator/src/main/java/org/ekstep/ep/samza/task/AssessmentAggregatorTask.java
data-pipeline/assessment-aggregator/src/test/java/org/ekstep/ep/samza/task/AssessmentAggregatorTest.java

Issue #SC-1459 : Added logs and improved code coverage

---

data-pipeline/redis-updater/src/main/java/org/ekstep/ep/samza/service/RedisUpdaterService.java
data-pipeline/redis-updater/src/test/java/org/ekstep/ep/samza/service/RedisUpdaterServiceTest.java

Issue #SC-000 : Fixed signintype issue while udpating userdetails

---

ansible/roles/analytics-druid/defaults/main.yml
ansible/roles/analytics-druid/tasks/install.yml
ansible/roles/analytics-druid/templates/router/jvm.config
ansible/roles/analytics-druid/templates/router/log4j2.xml
ansible/roles/analytics-druid/templates/router/runtime.properties

Issue #SC-1458 feat: Druid router role provisioning scripts

---

ansible/roles/analytics-api-deploy/templates/conf.j2

Issue #SB-15961 feat: Add config for DeviceProfileActor

---

ansible/roles/data-products-deploy/templates/common.conf.j2

Reverts project-sunbird/sunbird-data-pipeline#535

Revert "replaced swarm manager lb ip with private ingress ip (#534)"

---

data-pipeline/de-normalization/src/test/java/org/ekstep/ep/samza/fixtures/EventFixture.java

Issue #SC-000 : Fix the test case for older date

---

data-pipeline/ep-core/src/main/java/org/ekstep/ep/samza/core/JobMetrics.java

Issue #SC-000 : Fix the metrics issue in telemetry router

---

ansible/roles/analytics-api-deploy/templates/conf.j2
data-pipeline/de-normalization/src/test/java/org/ekstep/ep/samza/fixtures/EventFixture.java
data-pipeline/device-profile-updater/src/main/java/org/ekstep/ep/samza/service/DeviceProfileUpdaterService.java
data-pipeline/telemetry-location-updater/src/main/java/org/ekstep/ep/samza/domain/DeviceProfile.java
data-pipeline/telemetry-location-updater/src/main/java/org/ekstep/ep/samza/domain/Event.java
data-pipeline/telemetry-location-updater/src/main/java/org/ekstep/ep/samza/service/TelemetryLocationUpdaterService.java
data-pipeline/telemetry-location-updater/src/main/java/org/ekstep/ep/samza/util/DeviceProfileCache.java
data-pipeline/telemetry-location-updater/src/test/java/org/ekstep/ep/samza/fixtures/EventFixture.java
data-pipeline/telemetry-location-updater/src/test/java/org/ekstep/ep/samza/system/DeviceProfileTest.java
data-pipeline/telemetry-location-updater/src/test/java/org/ekstep/ep/samza/task/TelemetryLocationUpdaterTaskTest.java
data-pipeline/telemetry-location-updater/src/test/java/org/ekstep/ep/samza/util/DeviceProfileCacheTest.java

Issue #000 feat: Merge 2.5.0 hotfix changes

---

ansible/roles/druid-ingestion/templates/pipeline_metrics_index_kafka
ansible/roles/ep_logstash/templates/logstash.conf.indexer.pipeline_metrics
ansible/roles/setup-kafka/defaults/main.yml
data-pipeline/distribution/pom.xml
data-pipeline/ep-core/src/main/java/org/ekstep/ep/samza/core/JobMetrics.java

- Update ansible role to create new kafka topic "telemetry.assess.failed"
- Add new metrics to druid ingestion spec and logstash configurations
- Version changes in distribution pom.xml

Add new kafka topic and metrics into ansible

---

ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/tasks/main.yml

1. Added course-dashboard metrics, desktop-consumption-report to job list
2. increased the jobs count
3. Removing reports jobs from the cron list

Data products config update

---

ansible/roles/data-products-deploy/defaults/main.yml

Reverts project-sunbird/sunbird-data-pipeline#595

Revert "#SC-1465: Added audit-metrics-report in analytics job list"

---

data-pipeline/assessment-aggregator/src/main/java/org/ekstep/ep/samza/domain/Aggregate.java
data-pipeline/assessment-aggregator/src/test/java/org/ekstep/ep/samza/task/AssessmentAggregatorTest.java

Issue #SC-000 : Fix date issue for grand total in report

---

ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/druid-ingestion/templates/telemetry_index_kafka
data-pipeline/de-normalization/src/test/java/org/ekstep/ep/samza/fixtures/EventFixture.java

Issue #SC-000 - Add content play progress from end events to druid

---

ansible/roles/analytics-api-deploy/defaults/main.yml
ansible/roles/analytics-api-deploy/tasks/main.yml
ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/tasks/main.yml
ansible/roles/data-products-deploy/templates/replay-job.j2
ansible/roles/data-products-deploy/templates/replay-updater.j2
ansible/roles/data-products-deploy/templates/run-job.j2
ansible/roles/data-products-deploy/templates/start-jobmanager.j2
pipelines/deploy/analytics-api/Jenkinsfile
pipelines/deploy/data-products/Jenkinsfile

This PR is related to ansible changes for the newly created repos (core, service & data products)

Ansible changes 

---

ansible/roles/analytics-spark-provision/defaults/main.yml
ansible/roles/analytics-spark-provision/tasks/main.yml
ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/templates/common.conf.j2
ansible/roles/data-products-deploy/templates/replay-job.j2
ansible/roles/data-products-deploy/templates/replay-updater.j2
ansible/roles/data-products-deploy/templates/run-job.j2
ansible/roles/data-products-deploy/templates/start-jobmanager.j2
ansible/roles/data-products-deploy/templates/submit-job.j2

Ansible provision changes to upgrade the spark to 2.4.4

Spark upgrade - 2.4.4

---

ansible/portal.yml
ansible/roles/portal-dashboard/defaults/main.yml
ansible/roles/portal-dashboard/tasks/main.yml
pipelines/deploy/datascience/Jenkinsfile

@SanthoshVasabhaktula : Please review it.

Adding Portal dashboard' reports deploy configuration

---

ansible/roles/druid-ingestion/templates/pipeline_metrics_index_kafka

… pipeline metrics ingestion spec

 Added "share-route-success-count" metrics to druid pipeline metrics ingestion spec

---

ansible/druid-provision.yml
ansible/roles/analytics-druid/defaults/main.yml
ansible/roles/analytics-druid/templates/historical/jvm.config
ansible/roles/analytics-druid/templates/historical/runtime.properties

@SanthoshVasabhaktula @RevathiKotla

Issue #000 chore: Druid resizing changes

---

data-pipeline-flink/de-duplication/pom.xml
data-pipeline-flink/de-duplication/src/main/scala/org/sunbird/dp/task/DeduplicationStreamTask.scala
data-pipeline-flink/dp-core/pom.xml
data-pipeline-flink/dp-core/src/main/scala/org/sunbird/dp/serde/EventSerde.scala
data-pipeline-flink/dp-core/src/main/scala/org/sunbird/dp/serde/MapSerde.scala
data-pipeline-flink/dp-core/src/main/scala/org/sunbird/dp/serde/StringSerde.scala
data-pipeline-flink/dp-core/src/main/scala/org/sunbird/dp/task/BaseStreamTask.scala
data-pipeline-flink/dp-telemetry-reader/pom.xml
data-pipeline-flink/pipeline-preprocessor/pom.xml
data-pipeline-flink/pipeline-preprocessor/src/main/scala/org/sunbird/dp/task/PipelinePreprocessorStreamTask.scala

Issue # SC-1359 chore: Implement SerDe for Map data structure

---

ansible/roles/postgres/tasks/main.yml

@SanthoshVasabhaktula : Please review it

Adding report table for portal dashboard

---

ansible/roles/lpa-telemetry-backup-deploy/defaults/main.yml

Issue #000 chore: Secor process for ingestion cluster telemetry

---

ansible/roles/lpa-telemetry-backup-deploy/defaults/main.yml

Issue #000 chore: Fix zookeeper port for ingestion backup

---

ansible/roles/lpa-telemetry-backup-deploy/defaults/main.yml

Issue #000 chore: Fix ingestion kafka cluster variable names

---

ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/templates/common.conf.j2
ansible/roles/data-products-deploy/templates/model-config.json.j2
ansible/roles/data-products-deploy/templates/submit-all-jobs.rb.j2

- Update wfs config for parallelization and filters
- Fix submit job script kafka host issue
- Fix druid rollup host and port
- Stop Course and ETB jobs

Ansible changes for data products config fixes

---

ansible/roles/postgres/tasks/main.yml

@SanthoshVasabhaktula : Please review it.

Adding report_summary table for portal dashboard

---

data-pipeline-flink/assessment-aggregator/src/main/scala/org/sunbird/dp/assessment/functions/AssessmentAggregatorFunction.scala
data-pipeline-flink/assessment-aggregator/src/main/scala/org/sunbird/dp/assessment/task/AssessmentAggregatorConfig.scala
data-pipeline-flink/assessment-aggregator/src/main/scala/org/sunbird/dp/assessment/task/AssessmentAggregatorStreamTask.scala
data-pipeline-flink/content-cache-updater/src/main/scala/org/sunbird/dp/contentupdater/functions/ContentUpdaterFunction.scala
data-pipeline-flink/content-cache-updater/src/main/scala/org/sunbird/dp/contentupdater/functions/DialCodeUpdaterFunction.scala
data-pipeline-flink/content-cache-updater/src/main/scala/org/sunbird/dp/contentupdater/task/ContentCacheUpdaterConfig.scala
data-pipeline-flink/content-cache-updater/src/main/scala/org/sunbird/dp/contentupdater/task/ContentCacheUpdaterStreamTask.scala
data-pipeline-flink/de-normalization/src/main/scala/org/sunbird/dp/denorm/task/DenormalizationConfig.scala
data-pipeline-flink/de-normalization/src/main/scala/org/sunbird/dp/denorm/task/DenormalizationStreamTask.scala
data-pipeline-flink/device-profile-updater/src/main/scala/org/sunbird/dp/deviceprofile/task/DeviceProfileUpdaterConfig.scala
data-pipeline-flink/device-profile-updater/src/main/scala/org/sunbird/dp/deviceprofile/task/DeviceProfileUpdaterStreamTask.scala
data-pipeline-flink/dp-core/src/main/scala/org/sunbird/dp/core/domain/Events.scala
data-pipeline-flink/dp-core/src/main/scala/org/sunbird/dp/core/reader/Telemetry.scala
data-pipeline-flink/dp-core/src/main/scala/org/sunbird/dp/core/util/FlinkUtil.scala
data-pipeline-flink/druid-events-validator/src/main/scala/org/sunbird/dp/validator/functions/DruidRouterFunction.scala
data-pipeline-flink/druid-events-validator/src/main/scala/org/sunbird/dp/validator/task/DruidValidatorConfig.scala
data-pipeline-flink/druid-events-validator/src/main/scala/org/sunbird/dp/validator/task/DruidValidatorStreamTask.scala
data-pipeline-flink/pipeline-preprocessor/src/main/scala/org/sunbird/dp/preprocessor/domain/Event.scala
data-pipeline-flink/pipeline-preprocessor/src/main/scala/org/sunbird/dp/preprocessor/domain/Models.scala
data-pipeline-flink/pipeline-preprocessor/src/main/scala/org/sunbird/dp/preprocessor/functions/ShareEventsFlattenerFunction.scala
data-pipeline-flink/pipeline-preprocessor/src/main/scala/org/sunbird/dp/preprocessor/task/PipelinePreprocessorConfig.scala
data-pipeline-flink/pipeline-preprocessor/src/main/scala/org/sunbird/dp/preprocessor/task/PipelinePreprocessorStreamTask.scala
data-pipeline-flink/pipeline-preprocessor/src/test/scala/org/sunbird/dp/TestSchemaValidator.scala
data-pipeline-flink/pipeline-preprocessor/src/test/scala/org/sunbird/dp/fixture/EventFixture.scala
data-pipeline-flink/telemetry-extractor/src/main/scala/org/sunbird/dp/extractor/task/TelemetryExtractorConfig.scala
data-pipeline-flink/telemetry-extractor/src/main/scala/org/sunbird/dp/extractor/task/TelemetryExtractorStreamTask.scala
data-pipeline-flink/user-cache-updater/src/main/scala/org/sunbird/dp/usercache/functions/UserCacheUpdaterFunction.scala
data-pipeline-flink/user-cache-updater/src/main/scala/org/sunbird/dp/usercache/task/UserCacheUpdaterConfig.scala
data-pipeline-flink/user-cache-updater/src/main/scala/org/sunbird/dp/usercache/task/UserCacheUpdaterStreamTask.scala

Issue #000 chore: Flink distributed checkpointing changes

---

data-pipeline-flink/dp-core/src/main/scala/org/sunbird/dp/core/cache/DataCache.scala
data-pipeline-flink/dp-core/src/main/scala/org/sunbird/dp/core/cache/DedupEngine.scala
data-pipeline-flink/dp-core/src/main/scala/org/sunbird/dp/core/cache/RedisConnect.scala
data-pipeline-flink/dp-core/src/main/scala/org/sunbird/dp/core/job/BaseDeduplication.scala
data-pipeline-flink/dp-core/src/test/scala/org/sunbird/spec/CoreTestSpec.scala
data-pipeline-flink/user-cache-updater/src/test/scala/org/sunbird/dp/spec/UserCacheUpdatetStreamTaskSpec.scala

Reverts project-sunbird/sunbird-data-pipeline#825

Revert "Redis db 0 issue fixes in flink jobs"

---

ansible/roles/analytics-api-deploy/templates/conf.j2

@SanthoshVasabhaktula @sowmya-dixit

Issue #000 chore: Change redis max connections to 20 for a pool

---

data-pipeline-flink/telemetry-extractor/src/main/resources/telemetry-extractor.conf
data-pipeline-flink/telemetry-extractor/src/main/scala/org/sunbird/dp/extractor/functions/DeduplicationFunction.scala
data-pipeline-flink/telemetry-extractor/src/main/scala/org/sunbird/dp/extractor/task/TelemetryExtractorConfig.scala
data-pipeline-flink/telemetry-extractor/src/main/scala/org/sunbird/dp/extractor/task/TelemetryExtractorStreamTask.scala
data-pipeline-flink/telemetry-extractor/src/test/resources/test.conf
data-pipeline-flink/telemetry-extractor/src/test/scala/org/sunbird/dp/spec/TelemetryExtractionStreamTaskTestSpec.scala

… event into failed topic and batch failed event into batch failed topic

Flink extraction job issue fix

---

ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/tasks/main.yml
pipelines/deploy/ed-dataproducts/Jenkinsfile

**Parameters used for deployment:**
**Dev, Staging and Pre-prod**
remote = spark and module = dataproducts,default-jobs
**Prod:**
remote = spark and module = dataproducts,spark-jobs
remote = spark-1 and module = dataproducts,spark1-jobs

Enable Ed-dataproducts deployment to spark1 instance

---

ansible/roles/postgres/tasks/main.yml

@SanthoshVasabhaktula : Please review it

#HE-7 | Create and updation of report tables for parameterise access control for Hawkeye

---

data-pipeline-flink/druid-events-validator/src/main/resources/druid-events-validator.conf
data-pipeline-flink/druid-events-validator/src/main/scala/org/sunbird/dp/validator/functions/DruidRouterFunction.scala
data-pipeline-flink/druid-events-validator/src/main/scala/org/sunbird/dp/validator/functions/DruidValidatorFunction.scala
data-pipeline-flink/druid-events-validator/src/main/scala/org/sunbird/dp/validator/task/DruidValidatorConfig.scala
data-pipeline-flink/druid-events-validator/src/main/scala/org/sunbird/dp/validator/task/DruidValidatorStreamTask.scala
data-pipeline-flink/druid-events-validator/src/main/scala/org/sunbird/dp/validator/util/SchemaValidator.scala
data-pipeline-flink/druid-events-validator/src/test/scala/org/sunbird/dp/fixture/EventFixture.scala
data-pipeline-flink/druid-events-validator/src/test/scala/org/sunbird/dp/spec/DruidValidatorStreamTaskTestSpec.scala

1. Move the de-duplication to the DruidValidatorFunction.
2. Fix telemetry/summary router count metric as part of the move.

Issue #000 chore: Move deduplication to Validation function

---

ansible/roles/analytics-bootstrap-spark/tasks/main.yml
ansible/roles/postgres/tasks/main.yml

Following changes are added in this PR,
1. spark provision changes for private and public container changes added
2. superset database creation on Postgres service.
@SanthoshVasabhaktula : Please review it.

Issue #SB-19583 #HE-55 | spark provision changes and generalizing superset database

---

ansible/roles/analytics-bootstrap-spark/tasks/main.yml

@SanthoshVasabhaktula : Please review it

Issue #SB-19583 | Container name by env variable added

---

ansible/roles/analytics-bootstrap-spark/tasks/main.yml

@SanthoshVasabhaktula : Please review it.

#SB-19583 | Private & public container name changes added

---

ansible/roles/postgres/tasks/main.yml

@SanthoshVasabhaktula : Please review it

Report table changes added for Hawkeye

---

kubernetes/ansible/roles/sunbird-monitoring/defaults/main.yml
kubernetes/ansible/roles/sunbird-monitoring/templates/alertrules.yaml
kubernetes/ansible/roles/sunbird-monitoring/templates/prometheus-operator.yaml
kubernetes/helm_charts/monitoring/alertrules/templates/flinkjobs.yaml
kubernetes/helm_charts/monitoring/alertrules/templates/promrulesNode.yaml
kubernetes/helm_charts/monitoring/alertrules/values.yaml

This PR is to segregate the alerts type as critical and warning and send to two different channels.

Monitoring alerts enhancements

---

data-pipeline-flink/assessment-aggregator/src/main/scala/org/sunbird/dp/assessment/domain/Event.scala
data-pipeline-flink/assessment-aggregator/src/main/scala/org/sunbird/dp/assessment/functions/AssessmentAggregatorFunction.scala
data-pipeline-flink/content-cache-updater/src/main/scala/org/sunbird/dp/contentupdater/domain/Event.scala

Issue #000 fix: Remove LinkedTreeMap in cache updater jobs

---

data-pipeline-flink/ingest-router/src/main/scala/org/sunbird/dp/ingestrouter/task/IngestRouterConfig.scala
data-pipeline-flink/ingest-router/src/main/scala/org/sunbird/dp/ingestrouter/task/IngestRouterStreamTask.scala
data-pipeline-flink/ingest-router/src/test/resources/test.conf
data-pipeline-flink/ingest-router/src/test/scala/org/sunbird/dp/fixture/EventFixture.scala
data-pipeline-flink/ingest-router/src/test/scala/org/sunbird/dp/spec/IngestRouterStreamTaskTestSpec.scala
kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2

Added new Raw Router Job Configuration

Issue #TG-659 : Raw Router Job Configuration

---

data-pipeline-flink/assessment-aggregator/src/main/resources/assessment-aggregator.conf
data-pipeline-flink/assessment-aggregator/src/main/scala/org/sunbird/dp/assessment/functions/AssessmentAggregatorFunction.scala
data-pipeline-flink/assessment-aggregator/src/main/scala/org/sunbird/dp/assessment/task/AssessmentAggregatorConfig.scala
data-pipeline-flink/assessment-aggregator/src/main/scala/org/sunbird/dp/assessment/task/AssessmentAggregatorStreamTask.scala
data-pipeline-flink/assessment-aggregator/src/test/resources/test.conf
data-pipeline-flink/assessment-aggregator/src/test/resources/test.cql
data-pipeline-flink/assessment-aggregator/src/test/scala/org/sunbird/dp/spec/AssessmentAggregatorTaskTestSpec.scala
kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2

Assessment aggregator job is updated to push issue-certificate events for 100% progress enrolments.

SH-1368 feat: Changes to issue merit certificate events

---

ansible/roles/data-products-deploy/tasks/main.yml
ansible/roles/data-products-deploy/templates/submit-script.j2
pipelines/deploy/spark-cluster-deploy/Jenkinsfile

This PR includes the below feature, 
Submit the wfs jobs for failed partitions alone.

WFS jobs submit script enhancement

---

data-pipeline-flink/assessment-aggregator/src/main/resources/assessment-aggregator.conf
data-pipeline-flink/assessment-aggregator/src/main/scala/org/sunbird/dp/assessment/functions/AssessmentAggregatorFunction.scala
data-pipeline-flink/assessment-aggregator/src/main/scala/org/sunbird/dp/assessment/task/AssessmentAggregatorConfig.scala
data-pipeline-flink/assessment-aggregator/src/main/scala/org/sunbird/dp/assessment/task/AssessmentAggregatorStreamTask.scala
data-pipeline-flink/assessment-aggregator/src/test/resources/test.conf
data-pipeline-flink/assessment-aggregator/src/test/scala/org/sunbird/dp/spec/AssessmentAggregatorTaskTestSpec.scala
kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2

Ref release-3.7.0 Merged PR - https://github.com/project-sunbird/sunbird-data-pipeline/pull/1203

 Assessment Agg flink benchmark changes

---

ansible/roles/data-products-deploy/templates/submit-script.j2

Issue TG-886: Submit script fixes for single job submission issue

---

ansible/roles/data-products-deploy/tasks/main.yml
ansible/roles/data-products-deploy/templates/submit-script.j2
ansible/roles/data-products-deploy/templates/update-job-requests.py.j2

Issue #TG-886 feat: Parallel job submission - handle for 0 requests

---

ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/templates/submit-script.j2

Issue #TG-886 feat: Parallel job submission issue debug

---

pipelines/deploy/datascience/Jenkinsfile

Adding tag config to AdhocScript jenkinsfile

---

kubernetes/ansible/roles/secor-deploy/defaults/main.yaml

TG-928: Secor on Kubernetes - Env var config fixes

---

kubernetes/pipelines/deploy/secor/Jenkinsfile

Feat# TG-904: updated the jenkinsfile

---

kubernetes/ansible/roles/secor-deploy/defaults/main.yaml
kubernetes/helm_charts/secor/values.j2

This PR has secor process configuration changes to run parallel process on kubernetes along with servers. Will we revert this changes once it is completely verified and promoted to production.

TG-928: Secor on Kubernetes - Config changes for prod migration

---

kubernetes/helm_charts/datapipeline_jobs/templates/serviceMonitor.yaml

Issue: TG-904: added the condition check

---

ansible/inventory/env/group_vars/all.yml
kubernetes/ansible/bootstrap_minimal.yaml
kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml
kubernetes/ansible/roles/secor-deploy/defaults/main.yaml
kubernetes/helm_charts/bootstrap/reloader/.helmignore
kubernetes/helm_charts/bootstrap/reloader/Chart.yaml
kubernetes/helm_charts/bootstrap/reloader/templates/NOTES.txt
kubernetes/helm_charts/bootstrap/reloader/templates/_helpers.tpl
kubernetes/helm_charts/bootstrap/reloader/templates/clusterrole.yaml
kubernetes/helm_charts/bootstrap/reloader/templates/clusterrolebinding.yaml
kubernetes/helm_charts/bootstrap/reloader/templates/deployment.yaml
kubernetes/helm_charts/bootstrap/reloader/templates/role.yaml
kubernetes/helm_charts/bootstrap/reloader/templates/rolebinding.yaml
kubernetes/helm_charts/bootstrap/reloader/templates/serviceaccount.yaml
kubernetes/helm_charts/bootstrap/reloader/values.yaml
kubernetes/helm_charts/secor/templates/secor-statefulset.yaml
kubernetes/pipelines/bootstrap/Jenkinsfile

This change includes a config reloader installation and it is required to pod restart when there are config map changes. 

added the config reloader

---

ansible/inventory/env/group_vars/all.yml
ansible/roles/ansible-kafka-upgrade/defaults/main.yml
ansible/roles/setup-kafka/defaults/main.yml
ansible/roles/setup-kafka/tasks/main.yml

This PR includes the  below changes, 
Added the flink jobs kafka topics in setup-kafka ansible role and variablized the zookeeper ip. 

TG:942 - added the flink jobs topics in ansible role

---

ansible/roles/data-products-deploy/templates/common.conf.j2

This changes include fix for making merge container default value be configurable

TG-480: Add conf for default merge container

---

ansible/roles/druid-ingestion/templates/rollup_telemetry_hourly_syncts

This PR fixes an error with the hourly telemetry rollup ingestion specification.
N/A

TG-905: Fix JSON spec error

---

ansible/roles/druid-ingestion/templates/rollup_error_hourly_syncts
ansible/roles/druid-ingestion/templates/rollup_telemetry_hourly_syncts

This PR fixes ingestion spec parser error for telemetry hourly rollup druid data source.
N/A

TG-905: Fix telemetry hourly rollup ingestion spec

---

ansible/druid-anomaly-detection.yml
ansible/roles/druid-anomaly-detection/defaults/main.yml
ansible/roles/druid-anomaly-detection/tasks/main.yml
pipelines/deploy/druid-anomaly-detection/Jenkinsfile

This PR includes creation of Jenkinsfile for deployment of the druid based anomaly detection module. It also includes changes to the deployment directory and artifact naming convention in the anomaly detection deployment ansible role.
The ansible playbook role has been run to verify if the deployment is successful

TG-905: Deployment Jenkinsfile for anomaly detection

---

ansible/roles/druid-anomaly-detection/defaults/main.yml

This PR will fix the name of the telemetry data source in the anomaly detection config
N/A

TG-905: Fix telemetry datasource name in the anomaly detection config

---

ansible/roles/druid-anomaly-detection/templates/supervisor.conf.j2

This PR is for fixing the username and groupname for the supervisord configuration for the anomaly detection module
The changes have been tested by running the ansible script in the dev environment

TG-905: Fix user and group name in supervisord config

---

ansible/inventory/env/group_vars/all.yml

This PR includes the kafka topic creation role related variables updates

Fix #TG-979 updated the ansible var

---

ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/tasks/main.yml
ansible/roles/data-products-deploy/templates/cluster-config.json.j2

This include fix for the configuring the Cassandra read configurations for the cluster data-product jobs

TG-965: Add the cassandra configs to increase timeouts for the cluster cassandra dependent jobs

---

data-pipeline-flink/sunbird-dp-distribution/pom.xml

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24667" title="SB-24667" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24667</a>  "Course progress exhaust", "user-info exhaust", and "Response exhaust" reports are blank
</td></table>
<br />
https://project-sunbird.atlassian.net/browse/SB-24667
This PR contains the removal of user-cache-updater from dp-distribution pom file

SB-24667: Removed user-cache-updater from dp-distribution pom file

---

ansible/roles/data-products-deploy/tasks/main.yml

TG-965: Fix the parallel job ansible script 

---

ansible/roles/analytics-druid/defaults/main.yml
ansible/roles/analytics-druid/templates/_common/common.runtime.properties

TG-979 enabled the druid sql queries

---

ansible/roles/data-products-deploy/templates/cluster-config.json.j2

Fix the missing comma issue in ansible config

---

kubernetes/ansible/roles/secor-deploy/defaults/main.yaml

This PR includes configuration for the error telemetry events Secor backup
N/A

TG-905: Secor backup config for error telemetry

---

ansible/spark-cluster-job-submit.yml

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24667" title="SB-24667" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24667</a>  "Course progress exhaust", "user-info exhaust", and "Response exhaust" reports are blank
</td></table>
<br />
https://project-sunbird.atlassian.net/browse/SB-24667

Issue #SB-24667: Update azure storage key name

---

ansible/roles/data-products-deploy/defaults/main.yml

TG-965: Disable dynamic allocation  for cluster jobs

---

ansible/roles/azure-hdinsight-spark-cluster/templates/create-cluster.sh.j2
ansible/roles/cassandra-restore/defaults/main.yml
ansible/roles/provision-geo-location-db/defaults/main.yml

- Use the inventory username instead of hardcoding as `deployer`
- Fixes https://github.com/project-sunbird/sunbird-community/discussions/352#discussion-3386485

fix: use the username defined in inventory hosts file

---

ansible/roles/druid-anomaly-detection/defaults/main.yml
ansible/roles/druid-ingestion/templates/rollup_telemetry_hourly_syncts

This PR will merge the 3.9.0 release branch to 4.0.0 branch
- [ X Bug fix (non-breaking change which fixes an issue)

Merge release-3.9.0 branch to release-4.0.0 branch

---

ansible/roles/druid-anomaly-detection/templates/config.json.j2

This PR will fix the config.json construction using jinja2 templates when multiple queries are defined in the anomaly detection configuration
The ansible role has been run to check if the config.json file construction is proper and valid.

TG-905: Fix config.json construct for anomaly detection

---

ansible/roles/druid-anomaly-detection/defaults/main.yml
ansible/roles/druid-anomaly-detection/tasks/main.yml
ansible/roles/druid-anomaly-detection/templates/config.json.j2
ansible/roles/druid-ingestion/templates/rollup_telemetry_hourly_syncts

Merge Release 3.9.0 into Release 4.0.0

---

ansible/roles/druid-anomaly-detection/defaults/main.yml

This PR will fix the cron expression to execute anomaly detection at the 0th minute of every hour.
This has been tested in the dev environment.

TG-905: Fix cron expression for anomaly detection

---

ansible/roles/analytics-druid/defaults/main.yml

This PR includes changes to upgrade druid to the latest version 0.21.1
The upgrade changes will be tested in the sunbird dev environment.

TG-992: Upgrade druid version to 0.21.1

---

ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/templates/common.conf.j2
ansible/roles/postgres-db-update/tasks/main.yml

This PR includes config additions and postgres table update changes for throttling changes of data exhaust requests.

Issue #TG-955 feat: Handle throttling of data exhaust requests - configuration changes

---

ansible/roles/data-products-deploy/defaults/main.yml

This PR has default variable format issue.

Handle throttling of data exhaust requests - fix deployment issue

---

ansible/roles/data-products-deploy/files/sourcing-ingestion-spec.json

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23540" title="SB-23540" target="_blank"><img alt="Epic" src="https://project-sunbird.atlassian.net/images/icons/issuetypes/epic.svg" />SB-23540</a>  Reports to be generated from Hawkeye infra using Druid
</td></table>
<br />
https://project-sunbird.atlassian.net/browse/SB-23540
SB-23540: Metrics spec change for sourcing summary datasource

Issue #SB-23540: Updated metricsSpec for sourcing summary ingestion datasource

---

ansible/roles/data-products-deploy/files/sourcing-ingestion-spec.json

https://project-sunbird.atlassian.net/browse/SB-23540
SB-23540

Added osid to sourcing ingestion spec

---

data-pipeline-flink/de-normalization/src/main/scala/org/sunbird/dp/denorm/functions/DenormalizationWindowFunction.scala
data-pipeline-flink/de-normalization/src/test/scala/org/sunbird/dp/fixture/EventFixture.scala
data-pipeline-flink/de-normalization/src/test/scala/org/sunbird/dp/spec/DenormalizationStreamTaskTestSpec.scala

This PR has fixes to denormalisation flink job to handle SUMMARY events.

Issue #TG-994 feat: Fix denorm job to handle SUMMARY events

---

ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/templates/common.conf.j2

Issue SC-000: Add variables for throught fix-parallel batch limit

---

kubernetes/ansible/roles/sunbird-monitoring/templates/dp_prometheus-adapter.yaml

This PR has fixes to denorm lag metrics in prometheus-adapter.

Issue #TG-1009 feat: Flink auto scaling changes - fix denorm lag metrics in prometheus-adapter

---

kubernetes/pipelines/monitoring/Jenkinsfile

updated the monitoring jenkinsfile

---

ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/templates/common.conf.j2

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25551" title="SB-25551" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-25551</a>  Enhancement in data exhaust jobs
</td></table>
<br />
https://project-sunbird.atlassian.net/browse/SB-25551
This PR consist config changes for enhancement in data exhaust jobs related to batchLimit per request

Issue #SB-25551: Config for enhancement in data exhuast jobs

---

ansible/roles/analytics-spark-provision/tasks/main.yml
ansible/roles/setup-kafka/tasks/main.yml

fix(spark): keyserver update
fix(kafka): update topic creation order

Fixes for keyserver and kafka

---

ansible/roles/provision-azure-spark-cluster/defaults/main.yml
ansible/roles/provision-azure-spark-cluster/tasks/main.yml

This PR has fixes to guice version fixes in HD spark cluster for exhaust jobs failure.

Issue #TG-1028 feat: Fix HD Cluster 4.0 issue with exhaust jobs execution

---

ansible/roles/druid-ingestion/templates/raw_telemetry_events

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25592" title="SB-25592" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-25592</a>  Indexing UTM parameters
</td></table>
<br />

SB-25592 | UTM params in druid ingestion spec

---

ansible/roles/druid-ingestion/templates/raw_telemetry_events

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25592" title="SB-25592" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-25592</a>  Indexing UTM parameters
</td></table>
<br />
Reverts project-sunbird/sunbird-data-pipeline#1376

"SB-25592 | Revert |  UTM params in druid ingestion spec"

---

data-pipeline-flink/de-normalization/src/main/scala/org/sunbird/dp/denorm/functions/DenormalizationWindowFunction.scala
data-pipeline-flink/de-normalization/src/main/scala/org/sunbird/dp/denorm/type/ContentDenormalization.scala

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25755" title="SB-25755" target="_blank"><img alt="Bug" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10303&avatarType=issuetype" />SB-25755</a>  Collection Name is Missing for the "enrol-complete" in the "Audit Rollup" Events 
</td></table>
<br />
https://project-sunbird.atlassian.net/browse/SB-25755

Issue #SB-25755: Loggers added for denorm job to verify AUDIT events

---

ansible/roles/ansible-kafka-upgrade/defaults/main.yml
ansible/roles/ansible-kafka-upgrade/templates/server.properties.j2
ansible/roles/zookeeper-upgrade/defaults/main.yml
ansible/roles/zookeeper-upgrade/handlers/main.yml
ansible/roles/zookeeper-upgrade/tasks/Debian.yml
ansible/roles/zookeeper-upgrade/tasks/main.yml
ansible/roles/zookeeper-upgrade/templates/zookeeper.service.j2

This PR includes the kafka and zookeeper version upgrade changes.

kafka and zookeeper version upgrade

---

ansible/roles/druid-ingestion/defaults/main.yml
ansible/roles/druid-ingestion/templates/rollup_course_completion_audit_syncts

This PR has new ingestion spec changes for Course Completion Audit Events

Issue #TG-1038 feat: Druid Ingestion spec for Course Completion Audit Events

---

data-pipeline-flink/de-normalization/src/main/scala/org/sunbird/dp/denorm/util/DenormBaseCache.scala

Add logs to debug denorm flink job metadata parsing issue

---

ansible/roles/zookeeper-upgrade/defaults/main.yml
ansible/roles/zookeeper-upgrade/tasks/Debian.yml
ansible/roles/zookeeper-upgrade/templates/zoo.cfg.j2

This PR includes the changes for zookeeper version upgrade.

TG-1002: Zookeeper ansible script version upgrade

---

ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/templates/common.conf.j2

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25480" title="SB-25480" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-25480</a>  UCI - Conversation assessment data exhaust for States
</td></table>
<br />

Issue #SB-25480 feat: UCI Exhaust - Refactor postgres config variables

---

kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2

Issue #TG-1043 feat: Add job manager process memory config to flink jobs

---

ansible/roles/ansible-kafka-upgrade/templates/server.properties.j2

fix: updated ansible variable

---

ansible/roles/ansible-kafka-upgrade/templates/server.properties.j2

Keshavprasadms patch 1

---

data-pipeline-flink/pipeline-preprocessor/src/main/resources/schemas/telemetry/3.0/event.json
data-pipeline-flink/pipeline-preprocessor/src/main/resources/schemas/telemetry/3.0/metrics.json
data-pipeline-flink/pipeline-preprocessor/src/test/scala/org/sunbird/dp/fixture/EventFixture.scala
data-pipeline-flink/pipeline-preprocessor/src/test/scala/org/sunbird/dp/spec/PipelineProcessorStreamTaskTestSpec.scala

This PR includes schema validation changes for METRICS event.

Issue #TG-1055 feat: Add the METRICS event type to the validation schema in PipelinePreprocessor

---

ansible/roles/setup-kafka/defaults/main.yml

Adding ml topics to create SB-24105

---

ansible/redis_provision.yml
ansible/roles/azure-cli/tasks/main.yml
ansible/roles/redis-multiprocess-backup/defaults/main.yml
ansible/roles/redis-multiprocess-backup/tasks/main.yml
ansible/roles/redis-multiprocess/defaults/main.yml
ansible/roles/redis-multiprocess/tasks/main.yml
ansible/roles/redis-multiprocess/templates/redis.conf.j2
ansible/roles/redis/defaults/main.yml
ansible/roles/redis/tasks/main.yml
ansible/roles/redis/templates/redis.conf.j2
ansible/roles/redis/templates/systemd.j2
pipelines/provision/redis/Jenkinsfile

This PR includes the changes of redis version upgrade.

TG-1056: updated the redis role

---

ansible/roles/data-products-deploy/templates/submit-script.j2

Issue SC-000: Make the cluster submit to parallel execution

---

ansible/roles/content-snapshot-indexer/templates/conf/cassandraRedis.j2
ansible/roles/content-snapshot-indexer/templates/scripts/RedisUserDataIndexer.j2
ansible/roles/content-snapshot-indexer/templates/scripts/run-script.j2

Issue #0 | Shell script changes for user data indexer

---

ansible/roles/content-snapshot-indexer/tasks/main.yml

Ansible changes added ETL User cache indexer

---

pipelines/deploy/content-snapshot-indexer/Jenkinsfile

jenkinsfile changes added for ETL User cache indexer 

---

kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2

This PR includes auto scaling changes for summary denorm job.

Issue #TG-1085 fix: Enable auto scaling for Summary Denormalization job

---

data-pipeline-flink/user-cache-updater-2.0/src/main/scala/org/sunbird/dp/usercache/functions/UserCacheUpdaterFunctionV2.scala
data-pipeline-flink/user-cache-updater-2.0/src/main/scala/org/sunbird/dp/usercache/task/UserCacheUpdaterConfigV2.scala
data-pipeline-flink/user-cache-updater-2.0/src/main/scala/org/sunbird/dp/usercache/util/UserMetadataUpdater.scala
data-pipeline-flink/user-cache-updater-2.0/src/test/scala/org/sunbird/dp/fixture/EventFixture.scala
data-pipeline-flink/user-cache-updater-2.0/src/test/scala/org/sunbird/dp/spec/UserCacheUpdatetStreamTaskSpecV2.scala

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-26681" title="SB-26681" target="_blank"><img alt="Bug" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10303&avatarType=issuetype" />SB-26681</a>  Progress exhaust data across tenants - Numbers are reducing post 10th September
</td></table>
<br />
* Software …

SB-26681 | Removing empty fields for other pids fixes added in user-cache-updater

---

ansible/roles/data-products-deploy/templates/model-config.j2
ansible/roles/data-products-deploy/templates/run-job.j2

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-26355" title="SB-26355" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-26355</a>  Data correction script to discard users' attempt request if the request has incorrect number of questions
</td></table>
<br />
Reverts project-sunbird/sunbird-data-pipeline#1420

SB-26355 -   Revert " - Score metrics correction script job config"

---

ansible/roles/content-snapshot-indexer/tasks/main.yml
ansible/roles/content-snapshot-indexer/templates/conf/cassandraRedis.j2
ansible/roles/content-snapshot-indexer/templates/scripts/RedisUserDataIndexer.j2
ansible/roles/content-snapshot-indexer/templates/scripts/run-script.j2
data-pipeline-flink/dp-core/src/main/scala/org/sunbird/dp/core/cache/DataCache.scala
data-pipeline-flink/user-cache-updater-2.0/src/main/scala/org/sunbird/dp/usercache/functions/UserCacheUpdaterFunctionV2.scala
data-pipeline-flink/user-cache-updater-2.0/src/main/scala/org/sunbird/dp/usercache/task/UserCacheUpdaterConfigV2.scala
data-pipeline-flink/user-cache-updater-2.0/src/main/scala/org/sunbird/dp/usercache/util/UserMetadataUpdater.scala
data-pipeline-flink/user-cache-updater-2.0/src/test/scala/org/sunbird/dp/fixture/EventFixture.scala
data-pipeline-flink/user-cache-updater-2.0/src/test/scala/org/sunbird/dp/spec/UserCacheUpdatetStreamTaskSpecV2.scala
pipelines/deploy/content-snapshot-indexer/Jenkinsfile

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-26681" title="SB-26681" target="_blank"><img alt="Bug" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10303&avatarType=issuetype" />SB-26681</a>  Progress exhaust data across tenants - Numbers are reducing post 10th September
</td></table>
<br />
* Software …

SB-26681 | 4.1 user cache indexer changes added

---

ansible/roles/data-products-deploy/templates/model-config.j2
ansible/roles/data-products-deploy/templates/run-job.j2

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-26355" title="SB-26355" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-26355</a>  Data correction script to discard users' attempt request if the request has incorrect number of questions
</td></table>
<br />
**Test …

SB-26355 :  Job config update

---

pipelines/deploy/PopulatePSQL-ConsumerChannelMapping/Jenkinsfile

- playbook has been ranmed to postgres-db-update.yml

fix: playbook has been renamed to postgres-db-update.yml

---

ansible/roles/postgres-db-update/tasks/main.yml

Issue #TG-1069 fix: Dataset Meta API & Exhaust API refactoring - postgres schema changes

---

ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/templates/common.conf.j2
ansible/roles/data-products-deploy/templates/run-job.j2

Issue #TG-1100 fix: Druid On-demand Exhaust Job config - classname issue fix

---

ansible/roles/postgres-db-update/tasks/main.yml

Issue #TG-1100 fix: Druid On-demand Exhaust Job refactoring - fix dataset_metadata postgres table primary key issue

---

ansible/roles/postgres-db-update/tasks/main.yml

Issue #TG-1100 fix: Update dataset_metadata table schema for dataset_sub_id field

---

data-pipeline-flink/de-normalization/src/test/scala/org/sunbird/dp/fixture/EventFixture.scala

Issue #0000 fix: Fix test case failures for Denorm Flink Job

---

ansible/roles/analytics-run-report/tasks/main.yml
ansible/roles/analytics-run-report/templates/interval.j2
pipelines/deploy/druid-run-report-job/Jenkinsfile

#TG-1134: Fix RunReportJob jenkins job issue with dynamic interval

---

kubernetes/helm_charts/monitoring/processing-kafka-exporter/templates/alertRules.yaml
kubernetes/helm_charts/monitoring/processing-kafka-exporter/values.yaml

updated kafka_broker_unavailable alert

---

kubernetes/helm_charts/datapipeline_jobs/values.j2

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24793" title="SB-24793" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-24793</a>  Assessments Archival - Jobs Implementation and testing
</td></table>
<br />
https://project-sunbird.atlassian.net/browse/SB-24793

SB-24793 - Assessment Agg Flink config column changes

---

ansible/roles/provision-azure-spark-cluster/defaults/main.yml

Issue #TG-1154 feat: Upgrade log4j version to 2.16.0 for Spark HD Cluster

---

ansible/roles/data-products-deploy/templates/update-job-requests.py.j2

SB-24962 | Parallelism for exhaust-v2 jobs fixes added

---

ansible/roles/data-products-deploy/templates/update-job-requests.py.j2

Merging release-4.5.0 into 4.6.0 branch

---

ansible/roles/analytics-druid/defaults/main.yml

Issue #TG-1167 feat: Upgrade Druid to 0.22.1 version

---

ansible/roles/analytics-spark-provision/tasks/main.yml
kubernetes/ansible/bootstrap_minimal.yaml

TG-1154 - Release 4.4.1 into 4.5.0

---

ansible/roles/analytics-spark-provision/tasks/main.yml
kubernetes/ansible/bootstrap_minimal.yaml

Release 4.5.0 into 4.6.0

---

data-pipeline-flink/assessment-aggregator/src/main/scala/org/sunbird/dp/assessment/functions/UserScoreAggregateFunction.scala
data-pipeline-flink/assessment-aggregator/src/test/scala/org/sunbird/dp/spec/AssessmentAggregatorTaskTestSpec.scala

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28398" title="SB-28398" target="_blank"><img alt="Bug" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />SB-28398</a>  Groups: -  The ActivityDashboard  throws 500 Errors 
</td></table>
<br />
* Hardware …

SB-28398 | Attempts count changes added

---

ansible/inventory/env/group_vars/all.yml
ansible/roles/data-products-deploy/defaults/main.yml

UCI config update

---

ansible/roles/data-products-deploy/templates/common.conf.j2

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28621" title="SB-28621" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10304?size=medium" />SB-28621</a>  "Total Plays" and "Average Rating" count is not updated even though content details job is run successfully
</td></table>
<br /> …

SB-28621 | Play session count fixes added

---

ansible/roles/data-products-deploy/defaults/main.yml

#000 fix: Updated the job config

---

ansible/roles/jdk11/tasks/main.yml

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28788" title="SB-28788" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28788</a>  Upgrade Sunbird Ed data products to Java 11 for security vulnerability fixes
</td></table>
<br />
* Software …

SB-28788 - JDK 11 Path update

---

ansible/roles/analytics-spark-provision/defaults/main.yml
ansible/roles/analytics-spark-provision/tasks/main.yml
ansible/roles/jdk11/tasks/main.yml
ansible/roles/provision-azure-spark-cluster/defaults/main.yml
ansible/roles/provision-azure-spark-cluster/tasks/main.yml

Ansible update

---

ansible/roles/analytics-spark-provision/tasks/main.yml

Ansible update - Spark Provision Ruby Version Update

---

ansible/inventory/env/group_vars/all.yml
ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/templates/common.conf.j2

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-29391" title="SB-29391" target="_blank"><img alt="Bug" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />SB-29391</a>  Score is not available on the Course Progress report
</td></table>
<br />
* Hardware …

SB-29391 | Exhaust job Primary category config added

---

ansible/roles/data-products-deploy/tasks/main.yml

Issue #TG-1177 feat: Fix azure upload failure in deployment jobs

---

ansible/roles/data-products-deploy/templates/run-job.j2

Ansible run job script update

---

ansible/roles/druid-ingestion/templates/raw_sl_observation
ansible/roles/druid-ingestion/templates/raw_sl_observation_status
ansible/roles/druid-ingestion/templates/raw_sl_project_index

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28245" title="SB-28245" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28245</a>  Program Dashboard - Program Datasets
</td></table>
<br />

feat: SB-28245 push updated ml spec as part of SB-28245

---

ansible/roles/analytics-bootstrap-always/tasks/main.yml
ansible/roles/analytics-druid/defaults/main.yml
ansible/roles/analytics-spark-provision/defaults/main.yml
ansible/roles/provision-geo-location-db/tasks/main.yml

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-29848" title="SB-29848" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-29848</a>  Parallel Staging environment creation to support building blocks
</td></table>
<br />
* …

fix: SB-29848 Analytics job fixes

---

ansible/roles/analytics-druid/defaults/main.yml

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-29848" title="SB-29848" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-29848</a>  Parallel Staging environment creation to support building blocks
</td></table>
<br />
* …

fix: SB-29848 fix typo

---

ansible/roles/analytics-druid/templates/_common/common.runtime.properties
kubernetes/ansible/roles/druid/defaults/main.yml

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-29848" title="SB-29848" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-29848</a>  Parallel Staging environment creation to support building blocks
</td></table>
<br />
* …

fix: SB-29848 fix typos

---

ansible/roles/setup-kafka/defaults/main.yml

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-29848" title="SB-29848" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-29848</a>  Parallel Staging environment creation to support building blocks
</td></table>
<br />
* …

fix: SB-29848 Add kafka topics

---

ansible/roles/postgres-db-update/tasks/main.yml

Postgres report table changes added

---

ansible/roles/data-products-deploy/templates/common.conf.j2

Merging 4.9.0 to 4.9.5

---

ansible/roles/postgres-db-update/tasks/main.yml

Merge latest 4.10.0 changes to 4.10.5 branch

---

ansible/roles/content-snapshot-indexer/defaults/main.yml

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28238" title="SB-28238" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28238</a>  Migrate to Java 11 & Spark 3.1 for Sunbird Data Products
</td></table>
<br />
* Hardware …

SB-28238 -  Spark upgrade in the ETL Jobs

---

ansible/roles/druid-ingestion/templates/raw_ml_obs_domain_criteria_index
ansible/roles/druid-ingestion/templates/raw_ml_obs_domain_index
ansible/roles/druid-ingestion/templates/raw_ml_obs_status_index
ansible/roles/druid-ingestion/templates/raw_ml_project_status_index

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-29961" title="SB-29961" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-29961</a>  Distinct Count Issue in the HawkEye ML Reports
</td></table>
<br />

SB-29961 - ml new ingestion specs and datasource name change

---

ansible/roles/druid-ingestion/templates/raw_ml_obs_domain_criteria_index
ansible/roles/druid-ingestion/templates/raw_ml_obs_domain_index
ansible/roles/druid-ingestion/templates/raw_ml_obs_status_index
ansible/roles/druid-ingestion/templates/raw_ml_project_program_level_index
ansible/roles/druid-ingestion/templates/raw_ml_project_status_index
ansible/roles/druid-ingestion/templates/raw_sl_observation
ansible/roles/druid-ingestion/templates/raw_sl_observation_status
ansible/roles/druid-ingestion/templates/raw_sl_project_index
ansible/roles/druid-ingestion/templates/raw_sl_survey
ansible/roles/postgres-db-update/tasks/main.yml

Merge latest Release 4.10.0 changes into Release 4.10.5

---

ansible/roles/druid-ingestion/templates/raw_ml_obs_domain_criteria_index
ansible/roles/druid-ingestion/templates/raw_ml_obs_domain_index
ansible/roles/druid-ingestion/templates/raw_ml_obs_status_index
ansible/roles/druid-ingestion/templates/raw_ml_project_program_level_index
ansible/roles/druid-ingestion/templates/raw_ml_project_status_index
ansible/roles/druid-ingestion/templates/raw_sl_observation
ansible/roles/druid-ingestion/templates/raw_sl_observation_status
ansible/roles/druid-ingestion/templates/raw_sl_project_index
ansible/roles/druid-ingestion/templates/raw_sl_survey
ansible/roles/postgres-db-update/tasks/main.yml

Merge latest Release 4.10.5 changes into Release 5.0.0

---

ansible/roles/analytics-druid/defaults/main.yml

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23100" title="SB-23100" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-23100</a>  Creation of SL Druid Roll up Data sources for Reports
</td></table>
<br />
* Hardware …

SB-23100 - Adding Druid Extension for HLL Support

---

ansible/roles/druid-ingestion/defaults/main.yml
ansible/roles/druid-ingestion/templates/rollup_ml_observation_status
ansible/roles/druid-ingestion/templates/rollup_ml_project_status
ansible/roles/druid-ingestion/templates/rollup_ml_survey_status

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23100" title="SB-23100" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-23100</a>  Creation of SL Druid Roll up Data sources for Reports
</td></table>
<br />

SB-23100 - Add Rollup Specs

---

ansible/roles/druid-ingestion/templates/rollup_ml_project_status
ansible/roles/druid-ingestion/templates/rollup_ml_survey_status

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23100" title="SB-23100" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-23100</a>  Creation of SL Druid Roll up Data sources for Reports
</td></table>
<br />
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23100" title="SB-23100" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-23100</a>  Creation of SL Druid Roll up Data sources for Reports
</td></table>
<br />
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any …

SB-23100 - Update column name & expr

---

ansible/roles/druid-ingestion/templates/rollup_ml_survey_status

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23100" title="SB-23100" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-23100</a>  Creation of SL Druid Roll up Data sources for Reports
</td></table>
<br />
* Hardware …

SB-23100 - Add column to spec

---

ansible/roles/secor-fetch-logs/tasks/main.yml

fix: remove invalid arg

---

ansible/artifacts-download.yml
ansible/artifacts-upload.yml
ansible/roles/cassandra-backup/tasks/main.yml
ansible/roles/es-azure-snapshot/defaults/main.yml
ansible/roles/es-gcs-snapshot/defaults/main.yml
ansible/roles/es-s3-snapshot/defaults/main.yml
ansible/roles/influxdb_backup/tasks/main.yml
ansible/roles/influxdb_restore/tasks/main.yml
ansible/roles/postgres-managed-service-restore/tasks/main.yml
ansible/roles/postgres-managed-service/tasks/main.yml
ansible/roles/postgresql-backup/tasks/main.yml
ansible/roles/postgresql-restore/tasks/main.yml
ansible/roles/redis-backup/tasks/main.yml
ansible/roles/redis-multiprocess-backup/tasks/main.yml
ansible/roles/redis-multiprocess-restore/tasks/main.yml
ansible/roles/redis-restore/tasks/main.yml

Release 5.1.0 - CSP changes
