Sunbird-Obsrv/sunbird-data-pipeline

ansible/roles/yarn/templates/yarn-site.xml

We identified that, whenever nodemanager getting restarted the process/containers become orphan process. To prevent this need to add this yarn.nodemanager.recovery.enabled flag and it requires nodemanager restart in all the yarn-slaves.

Issue #DO-587 feat: Add yarn.nodemanager.recovery.enabled flag to yarn-site.xml

---

druid/ingestion-spec/summary_index_kafka.json
druid/ingestion-spec/telemetry_index_kafka.json

@anandp504 
Added below fields into in both `summary` and `telemetry` ingestion spec.
1. `statecustomname`
2. `districtcustom`
3. `statecustomcode`
4. `roles`
4. `mid`
5. `edata_plugin_id`
6. `edata_plugin_ver`
7. `edata_plugin_category`

Druid Ingestion Spec Update 

---

druid/ingestion-spec/telemetry_index_kafka.json

edata.props field needs to be added for the AUDIT events into Druid
ingestion spec for telemetry events. edata.props will have datatype of
List<String>.

Issue#000 feat: Add edata.props field from AUDIT event

---

ansible/roles/zookeeper-upgrade/templates/zoo.cfg.j2

With the old syntax, ips were not updated correctly and this addition is required to update the kafka cluster ips

Feat #0000: updated the ansible syntax to take the cluster ips

---

ansible/druid-ingestion.yml

This change is required to run the ingestion task on coordinator host group.

DO-1021 updated the hostname to coordinator

---

ansible/roles/data-products-deploy/templates/common.conf.j2

Changed the elastic search index name from `cbatch` to `course-batch`
@anandp504 @sunilpes

[SB-14182] course metrics dashboard elastic search index name change

---

ansible/roles/ep_logstash/templates/logstash.conf.indexer.device_api_metrics

Changed codec to plain for device logs to avoid new line insertion in kafka messages and secor backup.

Issue #SB-14300 - changed codec to plain for device logs

---

ansible/roles/data-products-deploy/templates/common.conf.j2

Configuration for the assessment report data product to generate the report only for "SelfAssess" content types and best attempt score

Issue #SB-14867 fix: Assessment dp report config

---

ansible/roles/data-products-deploy/templates/common.conf.j2

Now admin reports goes directly into root folder inside "reports" container

Issue #SC-1407 update: removed folder "admin-user-reports".

---

ansible/roles/samza-jobs-alert/templates/samza_alerts

In this addition, we are taking newly deployed job pattern to monitor the samza job and no need to add the newly deployed samza job to samza-job-string file.

DO-1782 samza job monitoring enhancement

---

ansible/inventory/env/group_vars/all.yml
ansible/roles/analytics-api-deploy/templates/conf.j2
ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/templates/submit-script.j2

Script parameters:
**--job** - Job code. Ex: wfs
**--mode** - mode of execution. [via-partition, job-manager, run-job]
**--partitions** - partitions. Considered only if mode = via-partition.Default value is taken from unique kafka topic
**--parallelisatio**n - parallelisation. Considered only if mode = via-partition. Default value is 1
**--startDate** - start_date. Replay start date. Execution of jobs for older dates or multiple days.
**--endDate** - end_date. Replay end date. Execution of jobs for older dates or multiple days.
**--sparkMaster** - spark master URL. Used for submitting job to cluster.
Example:
- Running WFS via partition with default partitions(takes from kafka topic metadata) with parallelisation as 2
**./submit-script.sh --job wfs --mode via-partition --parallelisation …

WFS optimisations - submit-script implementation

---

data-pipeline-flink/user-cache-updater-2.0/src/main/resources/user-cache-updater-v2.conf
data-pipeline-flink/user-cache-updater-2.0/src/main/scala/org/sunbird/dp/usercache/task/UserCacheUpdaterConfigV2.scala
data-pipeline-flink/user-cache-updater-2.0/src/main/scala/org/sunbird/dp/usercache/util/UserMetadataUpdater.scala
data-pipeline-flink/user-cache-updater-2.0/src/test/resources/data.cql
data-pipeline-flink/user-cache-updater-2.0/src/test/scala/org/sunbird/dp/spec/UserCacheUpdatetStreamTaskSpecV2.scala

The PR consists of the following changes:
1. Stores rootorg user's orgname
2. Stores userchannel information 
3. Redis index pointing to new index

Issue #SC-1808: Storing Orgname and userchannel in cache

---

ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/templates/model-config.j2

Creating a variable for druid ingestion URL since to override `druid_rollup_cluster_ingestion_task_url` in the production env.

Collection Summary V2 - Updating the Druid Ingestion Task URL

---

ansible/roles/content-snapshot-indexer/defaults/main.yml

This fix is intended to resolve the issue with the blob storage account details to which the snapshot file is being uploaded to cloud storage. Currently, the snapshot file is being uploaded to a private blob storage account which causes the indexer to fail when downloading the snapshot file.
* Software versions: NA
* Hardware versions: NA

fix: SB-24008 Fix blob storage details for content model druid indexer

---

data-pipeline-flink/assessment-aggregator/src/main/resources/assessment-aggregator.conf
data-pipeline-flink/assessment-aggregator/src/main/scala/org/sunbird/dp/assessment/functions/AssessmentAggregatorFunction.scala
data-pipeline-flink/assessment-aggregator/src/main/scala/org/sunbird/dp/assessment/functions/UserScoreAggregateFunction.scala
data-pipeline-flink/assessment-aggregator/src/main/scala/org/sunbird/dp/assessment/task/AssessmentAggregatorConfig.scala
data-pipeline-flink/assessment-aggregator/src/main/scala/org/sunbird/dp/assessment/task/AssessmentAggregatorStreamTask.scala
data-pipeline-flink/assessment-aggregator/src/test/resources/test.conf
data-pipeline-flink/assessment-aggregator/src/test/resources/test.cql
data-pipeline-flink/assessment-aggregator/src/test/scala/org/sunbird/dp/spec/AssessmentAggregatorTaskTestSpec.scala
kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SC-2218" title="SC-2218" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SC-2218</a>  Groups to report activity scores in addition to progress
</td></table>
<br />
This PR includes changes to assessment-aggregator to populate best attempted scores in user_activity_agg. This is used in group aggregate API

SC-2218: Update scores in user activity agg

---

data-pipeline-flink/assessment-aggregator/src/main/scala/org/sunbird/dp/assessment/functions/AssessmentAggregatorFunction.scala
data-pipeline-flink/assessment-aggregator/src/test/scala/org/sunbird/dp/spec/AssessmentAggregatorTaskTestSpec.scala
data-pipeline-flink/dp-core/src/main/scala/org/sunbird/dp/core/util/CassandraUtil.scala

This fix for the changing the default consistency level from LOCAL_ONE to QUORUM for cassandra dependency jobs

TG-934: Fix the consistency level in flink job

---

data-pipeline-flink/user-cache-updater-2.0/src/main/resources/user-cache-updater-v2.conf
data-pipeline-flink/user-cache-updater-2.0/src/test/resources/test.conf
kubernetes/helm_charts/datapipeline_jobs/values.j2

This fix is an ansible change to support organisations field for userReadAPI in user-cache-updater-v2 flink job

SB-24258: Ansible changes for userRead API to take fields as organisations

---

ansible/roles/provision-azure-spark-cluster/defaults/main.yml
ansible/roles/provision-azure-spark-cluster/tasks/main.yml

Provision ansible changes for removing the guava 28 jar which is having conflicts with jcloud  and replacing with guava 24 vesrion jar in hdinsigts 4.0 upgrade.

TG-937: Ansible changes for guava jar dependency for HDInsights-4.0

---

kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml
kubernetes/helm_charts/datapipeline_jobs/templates/flink_job_configmap.yaml
kubernetes/helm_charts/datapipeline_jobs/templates/flink_job_deployment.yaml
kubernetes/helm_charts/datapipeline_jobs/values.j2

This PR is to control the log level for flink jobs. As part of this change we have introduced one ansible var **flink_jobs_log_level**. By using this var we can control the log level for flink jobs.

TG-953 added the flink jobs log level control mechanism

---

ansible/druid_anomaly_detection.yml
ansible/roles/druid-anomaly-detection/defaults/main.yml
ansible/roles/druid-anomaly-detection/tasks/main.yml
ansible/roles/druid-anomaly-detection/templates/supervisor.conf.j2

This PR includes the following changes:
1. Provision python 3.8 alongside existing 3.5 version. Also, set up python3-pip, python3-setuptools, python3.8-venv.
2. Install the anomaly_detection python module inside the virtualenv created.
3. Use supervisord to run anomaly_detection as a service.
The ansible playbook has been tested in the loadtest environment and verified that the python3.8, venv and supervisord are installed as expected. The anomaly_detection module is installed and runs using the python scheduler to run the queries.

TG-905: Use supervisord to run anomaly_detection 

---

ansible/roles/druid-anomaly-detection/defaults/main.yml
ansible/roles/druid-anomaly-detection/templates/supervisor.conf.j2

This PR includes changes to handle rollup and raw druid cluster broker hosts as a single variable. 
The ansible playbook has been tested with the inventory file having just the raw-broker group and both raw-broker and rollup-broker inventory groups.

TG-905: Variable to handle rollup and raw druid brokers

---

ansible/druid-ingestion.yml
ansible/inventory/env/group_vars/all.yml
ansible/roles/druid-ingestion/tasks/main.yml
pipelines/ops/druid/Jenkinsfile.ingestion

This PR includes the changes to deploy the ingestion spec into 2 different cluster by just selecting the ingestion spec name from jenkins job.

TG-979 - feature to deploy the ingestion spec into 2 different cluster

---

pipelines/ops/druid/Jenkinsfile.druidingestionalert
pipelines/ops/druid/Jenkinsfile.druidsegmentalert
pipelines/ops/druid/Jenkinsfile.ingestion

This PR fixes the issue of automatically using the available Jenkins node i.e. master instead of running the deployments on ops-slave nodes.

TG-905: Remove ops-slave node config from druid ingestion deployments

---

ansible/roles/druid-anomaly-detection/defaults/main.yml
ansible/roles/druid-anomaly-detection/templates/supervisor.conf.j2

This PR fixes the issue with the druid_broker_host ansible variable which is being overridden in the private repo for DruidQueryProcessor functionality.
N/A

TG-905: Fix the rollup broker host ansible variable

---

ansible/roles/analytics-druid/defaults/main.yml

This PR fixes the issue with using the druid_version variable as part of the Druid artifact download URL

TG-992: Update druid_version variable to 0.21.1

---

data-pipeline-flink/de-normalization/src/main/scala/org/sunbird/dp/denorm/functions/DenormalizationWindowFunction.scala
data-pipeline-flink/de-normalization/src/main/scala/org/sunbird/dp/denorm/type/ContentDenormalization.scala

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25755" title="SB-25755" target="_blank"><img alt="Bug" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10303&avatarType=issuetype" />SB-25755</a>  Collection Name is Missing for the "enrol-complete" in the "Audit Rollup" Events 
</td></table>
<br />
Reverts project-sunbird/sunbird-data-pipeline#1386

Issue #SB-25755: Revert | Loggers added for denorm job to verify AUDIT events

---

ansible/roles/postgres-db-update/tasks/main.yml

This PR has fixes to postgres update command to add new columns to dataset_metadata table issue

Issue #TG-1069 fix: Dataset Meta API & Exhaust API refactoring - postgres schema changes

---

ansible/roles/data-products-deploy/defaults/main.yml
ansible/roles/data-products-deploy/tasks/main.yml

The PR includes two things which are listed below.
1. Cron jobs for UCI private exhaust & UCI response exhaust jobs to run at 2AM daily.
2. Change the config of uci_pdata_id to "{{env}}.uci.{{sunbird_instance}}" for this to match the one we are using for telemetry events.

Cron jobs for UCI private & response exhaust
